// <auto-generated />
#pragma warning disable CS0612, CS0618
file unsafe class InterfaceInformation : global::System.Runtime.InteropServices.Marshalling.IIUnknownInterfaceType
{
    public static global::System.Guid Iid { get; } = new(new global::System.ReadOnlySpan<byte>(new byte[] { 95, 187, 241, 121, 110, 182, 229, 72, 182, 169, 21, 69, 195, 35, 202, 61 }));

    private static void** _vtable;
    public static void** ManagedVirtualMethodTable => _vtable != null ? _vtable : (_vtable = InterfaceImplementation.CreateManagedVirtualFunctionTable());
}

[global::System.Runtime.InteropServices.DynamicInterfaceCastableImplementationAttribute]
file unsafe partial interface InterfaceImplementation : global::DiaSharp.SDK.IDataSource
{
    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.SDK.IDataSource.GetLastError(out string error)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.IDataSource));
        bool __invokeSucceeded = default;
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out error);
        ushort* __error_native = default;
        int __retVal = default;
        try
        {
            {
                __retVal = ((delegate* unmanaged[MemberFunction]<void*, ushort**, int> )__vtable_native[3])(__this, &__error_native);
            }

            __invokeSucceeded = true;
            global::System.GC.KeepAlive(this);
            // Unmarshal - Convert native data to managed data.
            error = global::System.Runtime.InteropServices.Marshalling.BStrStringMarshaller.ConvertToManaged(__error_native);
        }
        finally
        {
            if (__invokeSucceeded)
            {
                // CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
                global::System.Runtime.InteropServices.Marshalling.BStrStringMarshaller.Free(__error_native);
            }
        }

        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.SDK.IDataSource.LoadDataFromPdb(string pdbPath)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.IDataSource));
        int __retVal;
        // Pin - Pin data in preparation for calling the P/Invoke.
        fixed (void* __pdbPath_native = &global::System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.GetPinnableReference(pdbPath))
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, ushort*, int> )__vtable_native[4])(__this, (ushort*)__pdbPath_native);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    unsafe int global::DiaSharp.SDK.IDataSource.LoadAndValidateDataFromPdb(string pdbPath, global::System.Guid* pdbSignature, uint signature, uint age)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.IDataSource));
        int __retVal;
        // Pin - Pin data in preparation for calling the P/Invoke.
        fixed (void* __pdbPath_native = &global::System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.GetPinnableReference(pdbPath))
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, ushort*, global::System.Guid*, uint, uint, int> )__vtable_native[5])(__this, (ushort*)__pdbPath_native, pdbSignature, signature, age);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    unsafe int global::DiaSharp.SDK.IDataSource.LoadDataForExe(string exePath, string searchPath, void* callback)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.IDataSource));
        int __retVal;
        // Pin - Pin data in preparation for calling the P/Invoke.
        fixed (void* __searchPath_native = &global::System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.GetPinnableReference(searchPath))
        fixed (void* __exePath_native = &global::System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.GetPinnableReference(exePath))
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, ushort*, ushort*, void*, int> )__vtable_native[6])(__this, (ushort*)__exePath_native, (ushort*)__searchPath_native, callback);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.SDK.IDataSource.LoadDataFromIStream(global::DiaSharp.Storage.IStream stream)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.IDataSource));
        void* __stream_native = default;
        int __retVal = default;
        try
        {
            // Marshal - Convert managed data to native data.
            __stream_native = (void*)global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.Storage.IStream>.ConvertToUnmanaged(stream);
            {
                __retVal = ((delegate* unmanaged[MemberFunction]<void*, void*, int> )__vtable_native[7])(__this, __stream_native);
            }

            global::System.GC.KeepAlive(this);
        }
        finally
        {
            // CleanupCallerAllocated - Perform cleanup of caller allocated resources.
            global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.Storage.IStream>.Free(__stream_native);
        }

        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.SDK.IDataSource.OpenSession(out global::DiaSharp.SDK.ISession session)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.IDataSource));
        bool __invokeSucceeded = default;
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out session);
        void* __session_native = default;
        int __retVal = default;
        try
        {
            {
                __retVal = ((delegate* unmanaged[MemberFunction]<void*, void**, int> )__vtable_native[8])(__this, &__session_native);
            }

            __invokeSucceeded = true;
            global::System.GC.KeepAlive(this);
            // Unmarshal - Convert native data to managed data.
            session = global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.SDK.ISession>.ConvertToManaged(__session_native);
        }
        finally
        {
            if (__invokeSucceeded)
            {
                // CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
                global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.SDK.ISession>.Free(__session_native);
            }
        }

        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    unsafe int global::DiaSharp.SDK.IDataSource.LoadDataFromCodeViewInfo(string executable, string searchPath, uint infoSize, byte* info, void* callback)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.IDataSource));
        int __retVal;
        // Pin - Pin data in preparation for calling the P/Invoke.
        fixed (void* __searchPath_native = &global::System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.GetPinnableReference(searchPath))
        fixed (void* __executable_native = &global::System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.GetPinnableReference(executable))
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, ushort*, ushort*, uint, byte*, void*, int> )__vtable_native[9])(__this, (ushort*)__executable_native, (ushort*)__searchPath_native, infoSize, info, callback);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    unsafe int global::DiaSharp.SDK.IDataSource.LoadDataFromMiscInfo(string executable, string searchPath, uint exeTimestamp, uint debugTimestamp, uint exeSize, uint infoSize, byte* info, void* callback)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.IDataSource));
        int __retVal;
        // Pin - Pin data in preparation for calling the P/Invoke.
        fixed (void* __searchPath_native = &global::System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.GetPinnableReference(searchPath))
        fixed (void* __executable_native = &global::System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.GetPinnableReference(executable))
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, ushort*, ushort*, uint, uint, uint, uint, byte*, void*, int> )__vtable_native[10])(__this, (ushort*)__executable_native, (ushort*)__searchPath_native, exeTimestamp, debugTimestamp, exeSize, infoSize, info, callback);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }
}

file unsafe partial interface InterfaceImplementation
{
    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_GetLastError(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, ushort** __error_native__param)
    {
        global::DiaSharp.SDK.IDataSource @this = default;
        ref ushort* __error_native = ref *__error_native__param;
        string error = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.IDataSource>(__this_native);
            __retVal = @this.GetLastError(out error);
            // Marshal - Convert managed data to native data.
            __error_native = (ushort*)global::System.Runtime.InteropServices.Marshalling.BStrStringMarshaller.ConvertToUnmanaged(error);
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_LoadDataFromPdb(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, ushort* __pdbPath_native)
    {
        global::DiaSharp.SDK.IDataSource @this = default;
        string pdbPath = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            pdbPath = global::System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.ConvertToManaged(__pdbPath_native);
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.IDataSource>(__this_native);
            __retVal = @this.LoadDataFromPdb(pdbPath);
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_LoadAndValidateDataFromPdb(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, ushort* __pdbPath_native, global::System.Guid* pdbSignature, uint signature, uint age)
    {
        global::DiaSharp.SDK.IDataSource @this = default;
        string pdbPath = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            pdbPath = global::System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.ConvertToManaged(__pdbPath_native);
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.IDataSource>(__this_native);
            __retVal = @this.LoadAndValidateDataFromPdb(pdbPath, pdbSignature, signature, age);
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_LoadDataForExe(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, ushort* __exePath_native, ushort* __searchPath_native, void* callback)
    {
        global::DiaSharp.SDK.IDataSource @this = default;
        string exePath = default;
        string searchPath = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            searchPath = global::System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.ConvertToManaged(__searchPath_native);
            exePath = global::System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.ConvertToManaged(__exePath_native);
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.IDataSource>(__this_native);
            __retVal = @this.LoadDataForExe(exePath, searchPath, callback);
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_LoadDataFromIStream(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, void* __stream_native)
    {
        global::DiaSharp.SDK.IDataSource @this = default;
        global::DiaSharp.Storage.IStream stream = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            stream = global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.Storage.IStream>.ConvertToManaged(__stream_native);
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.IDataSource>(__this_native);
            __retVal = @this.LoadDataFromIStream(stream);
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_OpenSession(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, void** __session_native__param)
    {
        global::DiaSharp.SDK.IDataSource @this = default;
        ref void* __session_native = ref *__session_native__param;
        global::DiaSharp.SDK.ISession session = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.IDataSource>(__this_native);
            __retVal = @this.OpenSession(out session);
            // Marshal - Convert managed data to native data.
            __session_native = (void*)global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.SDK.ISession>.ConvertToUnmanaged(session);
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_LoadDataFromCodeViewInfo(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, ushort* __executable_native, ushort* __searchPath_native, uint infoSize, byte* info, void* callback)
    {
        global::DiaSharp.SDK.IDataSource @this = default;
        string executable = default;
        string searchPath = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            searchPath = global::System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.ConvertToManaged(__searchPath_native);
            executable = global::System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.ConvertToManaged(__executable_native);
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.IDataSource>(__this_native);
            __retVal = @this.LoadDataFromCodeViewInfo(executable, searchPath, infoSize, info, callback);
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_LoadDataFromMiscInfo(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, ushort* __executable_native, ushort* __searchPath_native, uint exeTimestamp, uint debugTimestamp, uint exeSize, uint infoSize, byte* info, void* callback)
    {
        global::DiaSharp.SDK.IDataSource @this = default;
        string executable = default;
        string searchPath = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            searchPath = global::System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.ConvertToManaged(__searchPath_native);
            executable = global::System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.ConvertToManaged(__executable_native);
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.IDataSource>(__this_native);
            __retVal = @this.LoadDataFromMiscInfo(executable, searchPath, exeTimestamp, debugTimestamp, exeSize, infoSize, info, callback);
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }
}

file unsafe partial interface InterfaceImplementation
{
    internal static void** CreateManagedVirtualFunctionTable()
    {
        void** vtable = (void**)global::System.Runtime.CompilerServices.RuntimeHelpers.AllocateTypeAssociatedMemory(typeof(global::DiaSharp.SDK.IDataSource), sizeof(void*) * 11);
        {
            nint v0, v1, v2;
            global::System.Runtime.InteropServices.ComWrappers.GetIUnknownImpl(out v0, out v1, out v2);
            vtable[0] = (void*)v0;
            vtable[1] = (void*)v1;
            vtable[2] = (void*)v2;
        }

        {
            vtable[3] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, ushort**, int> )&ABI_GetLastError;
            vtable[4] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, ushort*, int> )&ABI_LoadDataFromPdb;
            vtable[5] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, ushort*, global::System.Guid*, uint, uint, int> )&ABI_LoadAndValidateDataFromPdb;
            vtable[6] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, ushort*, ushort*, void*, int> )&ABI_LoadDataForExe;
            vtable[7] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, void*, int> )&ABI_LoadDataFromIStream;
            vtable[8] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, void**, int> )&ABI_OpenSession;
            vtable[9] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, ushort*, ushort*, uint, byte*, void*, int> )&ABI_LoadDataFromCodeViewInfo;
            vtable[10] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, ushort*, ushort*, uint, uint, uint, uint, byte*, void*, int> )&ABI_LoadDataFromMiscInfo;
        }

        return vtable;
    }
}

namespace DiaSharp.SDK
{
    [global::System.Runtime.InteropServices.Marshalling.IUnknownDerivedAttribute<InterfaceInformation, InterfaceImplementation>]
    public partial interface IDataSource
    {
    }
}

namespace DiaSharp.SDK
{
    public partial interface IDataSource
    {
    }
}