// <auto-generated />
#pragma warning disable CS0612, CS0618
file unsafe class InterfaceInformation : global::System.Runtime.InteropServices.Marshalling.IIUnknownInterfaceType
{
    public static global::System.Guid Iid { get; } = new(new global::System.ReadOnlySpan<byte>(new byte[] { 210, 14, 228, 200, 217, 161, 33, 66, 134, 146, 60, 230, 97, 24, 75, 68 }));

    private static void** _vtable;
    public static void** ManagedVirtualMethodTable => _vtable != null ? _vtable : (_vtable = InterfaceImplementation.CreateManagedVirtualFunctionTable());
}

[global::System.Runtime.InteropServices.DynamicInterfaceCastableImplementationAttribute]
file unsafe partial interface InterfaceImplementation : global::DiaSharp.SDK.IImageData
{
    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.SDK.IImageData.GetRelativeVirtualAddress(out uint rva)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.IImageData));
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out rva);
        int __retVal;
        // Pin - Pin data in preparation for calling the P/Invoke.
        fixed (uint* __rva_native = &rva)
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, uint*, int> )__vtable_native[3])(__this, __rva_native);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.SDK.IImageData.GetVirtualAddress(out ulong va)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.IImageData));
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out va);
        int __retVal;
        // Pin - Pin data in preparation for calling the P/Invoke.
        fixed (ulong* __va_native = &va)
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, ulong*, int> )__vtable_native[4])(__this, __va_native);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.SDK.IImageData.GetImageBase(out ulong imageBase)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.IImageData));
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out imageBase);
        int __retVal;
        // Pin - Pin data in preparation for calling the P/Invoke.
        fixed (ulong* __imageBase_native = &imageBase)
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, ulong*, int> )__vtable_native[5])(__this, __imageBase_native);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }
}

file unsafe partial interface InterfaceImplementation
{
    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_GetRelativeVirtualAddress(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, uint* __rva_native__param)
    {
        global::DiaSharp.SDK.IImageData @this = default;
        ref uint __rva_native = ref *__rva_native__param;
        uint rva = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.IImageData>(__this_native);
            __retVal = @this.GetRelativeVirtualAddress(out rva);
            // Marshal - Convert managed data to native data.
            __rva_native = rva;
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_GetVirtualAddress(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, ulong* __va_native__param)
    {
        global::DiaSharp.SDK.IImageData @this = default;
        ref ulong __va_native = ref *__va_native__param;
        ulong va = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.IImageData>(__this_native);
            __retVal = @this.GetVirtualAddress(out va);
            // Marshal - Convert managed data to native data.
            __va_native = va;
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_GetImageBase(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, ulong* __imageBase_native__param)
    {
        global::DiaSharp.SDK.IImageData @this = default;
        ref ulong __imageBase_native = ref *__imageBase_native__param;
        ulong imageBase = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.IImageData>(__this_native);
            __retVal = @this.GetImageBase(out imageBase);
            // Marshal - Convert managed data to native data.
            __imageBase_native = imageBase;
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }
}

file unsafe partial interface InterfaceImplementation
{
    internal static void** CreateManagedVirtualFunctionTable()
    {
        void** vtable = (void**)global::System.Runtime.CompilerServices.RuntimeHelpers.AllocateTypeAssociatedMemory(typeof(global::DiaSharp.SDK.IImageData), sizeof(void*) * 6);
        {
            nint v0, v1, v2;
            global::System.Runtime.InteropServices.ComWrappers.GetIUnknownImpl(out v0, out v1, out v2);
            vtable[0] = (void*)v0;
            vtable[1] = (void*)v1;
            vtable[2] = (void*)v2;
        }

        {
            vtable[3] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, uint*, int> )&ABI_GetRelativeVirtualAddress;
            vtable[4] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, ulong*, int> )&ABI_GetVirtualAddress;
            vtable[5] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, ulong*, int> )&ABI_GetImageBase;
        }

        return vtable;
    }
}

namespace DiaSharp.SDK
{
    [global::System.Runtime.InteropServices.Marshalling.IUnknownDerivedAttribute<InterfaceInformation, InterfaceImplementation>]
    public partial interface IImageData
    {
    }
}

namespace DiaSharp.SDK
{
    public partial interface IImageData
    {
    }
}