// <auto-generated />
#pragma warning disable CS0612, CS0618
file unsafe class InterfaceInformation : global::System.Runtime.InteropServices.Marshalling.IIUnknownInterfaceType
{
    public static global::System.Guid Iid { get; } = new(new global::System.ReadOnlySpan<byte>(new byte[] { 220, 92, 96, 174, 5, 129, 35, 74, 183, 16, 50, 89, 241, 226, 97, 18 }));

    private static void** _vtable;
    public static void** ManagedVirtualMethodTable => _vtable != null ? _vtable : (_vtable = InterfaceImplementation.CreateManagedVirtualFunctionTable());
}

[global::System.Runtime.InteropServices.DynamicInterfaceCastableImplementationAttribute]
file unsafe partial interface InterfaceImplementation : global::DiaSharp.SDK.IInjectedSource
{
    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.SDK.IInjectedSource.GetCRC(out uint crc)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.IInjectedSource));
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out crc);
        int __retVal;
        // Pin - Pin data in preparation for calling the P/Invoke.
        fixed (uint* __crc_native = &crc)
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, uint*, int> )__vtable_native[3])(__this, __crc_native);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.SDK.IInjectedSource.GetLength(out ulong length)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.IInjectedSource));
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out length);
        int __retVal;
        // Pin - Pin data in preparation for calling the P/Invoke.
        fixed (ulong* __length_native = &length)
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, ulong*, int> )__vtable_native[4])(__this, __length_native);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.SDK.IInjectedSource.GetFilename(out string name)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.IInjectedSource));
        bool __invokeSucceeded = default;
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out name);
        ushort* __name_native = default;
        int __retVal = default;
        try
        {
            {
                __retVal = ((delegate* unmanaged[MemberFunction]<void*, ushort**, int> )__vtable_native[5])(__this, &__name_native);
            }

            __invokeSucceeded = true;
            global::System.GC.KeepAlive(this);
            // Unmarshal - Convert native data to managed data.
            name = global::System.Runtime.InteropServices.Marshalling.BStrStringMarshaller.ConvertToManaged(__name_native);
        }
        finally
        {
            if (__invokeSucceeded)
            {
                // CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
                global::System.Runtime.InteropServices.Marshalling.BStrStringMarshaller.Free(__name_native);
            }
        }

        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.SDK.IInjectedSource.GetObjectFilename(out string name)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.IInjectedSource));
        bool __invokeSucceeded = default;
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out name);
        ushort* __name_native = default;
        int __retVal = default;
        try
        {
            {
                __retVal = ((delegate* unmanaged[MemberFunction]<void*, ushort**, int> )__vtable_native[6])(__this, &__name_native);
            }

            __invokeSucceeded = true;
            global::System.GC.KeepAlive(this);
            // Unmarshal - Convert native data to managed data.
            name = global::System.Runtime.InteropServices.Marshalling.BStrStringMarshaller.ConvertToManaged(__name_native);
        }
        finally
        {
            if (__invokeSucceeded)
            {
                // CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
                global::System.Runtime.InteropServices.Marshalling.BStrStringMarshaller.Free(__name_native);
            }
        }

        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.SDK.IInjectedSource.GetVirtualFilename(out string name)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.IInjectedSource));
        bool __invokeSucceeded = default;
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out name);
        ushort* __name_native = default;
        int __retVal = default;
        try
        {
            {
                __retVal = ((delegate* unmanaged[MemberFunction]<void*, ushort**, int> )__vtable_native[7])(__this, &__name_native);
            }

            __invokeSucceeded = true;
            global::System.GC.KeepAlive(this);
            // Unmarshal - Convert native data to managed data.
            name = global::System.Runtime.InteropServices.Marshalling.BStrStringMarshaller.ConvertToManaged(__name_native);
        }
        finally
        {
            if (__invokeSucceeded)
            {
                // CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
                global::System.Runtime.InteropServices.Marshalling.BStrStringMarshaller.Free(__name_native);
            }
        }

        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.SDK.IInjectedSource.GetSourceCompression(out uint compression)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.IInjectedSource));
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out compression);
        int __retVal;
        // Pin - Pin data in preparation for calling the P/Invoke.
        fixed (uint* __compression_native = &compression)
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, uint*, int> )__vtable_native[8])(__this, __compression_native);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    unsafe int global::DiaSharp.SDK.IInjectedSource.GetSource(uint dataSize, out uint bytesWritten, byte* buffer)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.IInjectedSource));
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out bytesWritten);
        int __retVal;
        // Pin - Pin data in preparation for calling the P/Invoke.
        fixed (uint* __bytesWritten_native = &bytesWritten)
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, uint, uint*, byte*, int> )__vtable_native[9])(__this, dataSize, __bytesWritten_native, buffer);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }
}

file unsafe partial interface InterfaceImplementation
{
    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_GetCRC(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, uint* __crc_native__param)
    {
        global::DiaSharp.SDK.IInjectedSource @this = default;
        ref uint __crc_native = ref *__crc_native__param;
        uint crc = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.IInjectedSource>(__this_native);
            __retVal = @this.GetCRC(out crc);
            // Marshal - Convert managed data to native data.
            __crc_native = crc;
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_GetLength(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, ulong* __length_native__param)
    {
        global::DiaSharp.SDK.IInjectedSource @this = default;
        ref ulong __length_native = ref *__length_native__param;
        ulong length = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.IInjectedSource>(__this_native);
            __retVal = @this.GetLength(out length);
            // Marshal - Convert managed data to native data.
            __length_native = length;
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_GetFilename(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, ushort** __name_native__param)
    {
        global::DiaSharp.SDK.IInjectedSource @this = default;
        ref ushort* __name_native = ref *__name_native__param;
        string name = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.IInjectedSource>(__this_native);
            __retVal = @this.GetFilename(out name);
            // Marshal - Convert managed data to native data.
            __name_native = (ushort*)global::System.Runtime.InteropServices.Marshalling.BStrStringMarshaller.ConvertToUnmanaged(name);
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_GetObjectFilename(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, ushort** __name_native__param)
    {
        global::DiaSharp.SDK.IInjectedSource @this = default;
        ref ushort* __name_native = ref *__name_native__param;
        string name = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.IInjectedSource>(__this_native);
            __retVal = @this.GetObjectFilename(out name);
            // Marshal - Convert managed data to native data.
            __name_native = (ushort*)global::System.Runtime.InteropServices.Marshalling.BStrStringMarshaller.ConvertToUnmanaged(name);
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_GetVirtualFilename(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, ushort** __name_native__param)
    {
        global::DiaSharp.SDK.IInjectedSource @this = default;
        ref ushort* __name_native = ref *__name_native__param;
        string name = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.IInjectedSource>(__this_native);
            __retVal = @this.GetVirtualFilename(out name);
            // Marshal - Convert managed data to native data.
            __name_native = (ushort*)global::System.Runtime.InteropServices.Marshalling.BStrStringMarshaller.ConvertToUnmanaged(name);
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_GetSourceCompression(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, uint* __compression_native__param)
    {
        global::DiaSharp.SDK.IInjectedSource @this = default;
        ref uint __compression_native = ref *__compression_native__param;
        uint compression = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.IInjectedSource>(__this_native);
            __retVal = @this.GetSourceCompression(out compression);
            // Marshal - Convert managed data to native data.
            __compression_native = compression;
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_GetSource(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, uint dataSize, uint* __bytesWritten_native__param, byte* buffer)
    {
        global::DiaSharp.SDK.IInjectedSource @this = default;
        ref uint __bytesWritten_native = ref *__bytesWritten_native__param;
        uint bytesWritten = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.IInjectedSource>(__this_native);
            __retVal = @this.GetSource(dataSize, out bytesWritten, buffer);
            // Marshal - Convert managed data to native data.
            __bytesWritten_native = bytesWritten;
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }
}

file unsafe partial interface InterfaceImplementation
{
    internal static void** CreateManagedVirtualFunctionTable()
    {
        void** vtable = (void**)global::System.Runtime.CompilerServices.RuntimeHelpers.AllocateTypeAssociatedMemory(typeof(global::DiaSharp.SDK.IInjectedSource), sizeof(void*) * 10);
        {
            nint v0, v1, v2;
            global::System.Runtime.InteropServices.ComWrappers.GetIUnknownImpl(out v0, out v1, out v2);
            vtable[0] = (void*)v0;
            vtable[1] = (void*)v1;
            vtable[2] = (void*)v2;
        }

        {
            vtable[3] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, uint*, int> )&ABI_GetCRC;
            vtable[4] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, ulong*, int> )&ABI_GetLength;
            vtable[5] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, ushort**, int> )&ABI_GetFilename;
            vtable[6] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, ushort**, int> )&ABI_GetObjectFilename;
            vtable[7] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, ushort**, int> )&ABI_GetVirtualFilename;
            vtable[8] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, uint*, int> )&ABI_GetSourceCompression;
            vtable[9] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, uint, uint*, byte*, int> )&ABI_GetSource;
        }

        return vtable;
    }
}

namespace DiaSharp.SDK
{
    [global::System.Runtime.InteropServices.Marshalling.IUnknownDerivedAttribute<InterfaceInformation, InterfaceImplementation>]
    public partial interface IInjectedSource
    {
    }
}

namespace DiaSharp.SDK
{
    public partial interface IInjectedSource
    {
    }
}