// <auto-generated />
#pragma warning disable CS0612, CS0618
file unsafe class InterfaceInformation : global::System.Runtime.InteropServices.Marshalling.IIUnknownInterfaceType
{
    public static global::System.Guid Iid { get; } = new(new global::System.ReadOnlySpan<byte>(new byte[] { 156, 111, 65, 157, 132, 225, 178, 69, 164, 240, 206, 81, 127, 113, 158, 155 }));

    private static void** _vtable;
    public static void** ManagedVirtualMethodTable => _vtable != null ? _vtable : (_vtable = InterfaceImplementation.CreateManagedVirtualFunctionTable());
}

[global::System.Runtime.InteropServices.DynamicInterfaceCastableImplementationAttribute]
file unsafe partial interface InterfaceImplementation : global::DiaSharp.SDK.IPropertyStorage
{
    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    unsafe int global::DiaSharp.SDK.IPropertyStorage.ReadMultiple(uint specifierCount, global::DiaSharp.Storage.PropertySpecifier* specifiers, out void* PropVariant)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.IPropertyStorage));
        PropVariant = default;
        int __retVal;
        // Pin - Pin data in preparation for calling the P/Invoke.
        fixed (void** __PropVariant_native = &PropVariant)
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, uint, global::DiaSharp.Storage.PropertySpecifier*, void**, int> )__vtable_native[3])(__this, specifierCount, specifiers, __PropVariant_native);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    unsafe int global::DiaSharp.SDK.IPropertyStorage.ReadPropertyNames(uint propertyIDCount, uint* propertyIDs, out string[] names)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.IPropertyStorage));
        bool __invokeSucceeded = default;
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out names);
        global::System.IntPtr* __names_native = default;
        int __retVal = default;
        // Setup - Perform required setup.
        int __names_native__numElements;
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out __names_native__numElements);
        try
        {
            {
                __retVal = ((delegate* unmanaged[MemberFunction]<void*, uint, uint*, global::System.IntPtr**, int> )__vtable_native[4])(__this, propertyIDCount, propertyIDs, &__names_native);
            }

            __invokeSucceeded = true;
            global::System.GC.KeepAlive(this);
            // Unmarshal - Convert native data to managed data.
            __names_native__numElements = checked((int)(propertyIDCount));
            names = global::System.Runtime.InteropServices.Marshalling.ArrayMarshaller<string, global::System.IntPtr>.AllocateContainerForManagedElements(__names_native, __names_native__numElements);
            {
                global::System.ReadOnlySpan<global::System.IntPtr> __names_native__nativeSpan = global::System.Runtime.InteropServices.Marshalling.ArrayMarshaller<string, global::System.IntPtr>.GetUnmanagedValuesSource(__names_native, __names_native__numElements);
                global::System.Span<string> __names_native__managedSpan = global::System.Runtime.InteropServices.Marshalling.ArrayMarshaller<string, global::System.IntPtr>.GetManagedValuesDestination(names);
                for (int __i0 = 0; __i0 < __names_native__numElements; ++__i0)
                {
                    __names_native__managedSpan[__i0] = global::System.Runtime.InteropServices.Marshalling.BStrStringMarshaller.ConvertToManaged((ushort*)__names_native__nativeSpan[__i0]);
                }
            }
        }
        finally
        {
            if (__invokeSucceeded)
            {
                // CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
                {
                    global::System.ReadOnlySpan<global::System.IntPtr> __names_native__nativeSpan = global::System.Runtime.InteropServices.Marshalling.ArrayMarshaller<string, global::System.IntPtr>.GetUnmanagedValuesSource(__names_native, __names_native__numElements);
                    for (int __i0 = 0; __i0 < __names_native__nativeSpan.Length; ++__i0)
                    {
                        global::System.Runtime.InteropServices.Marshalling.BStrStringMarshaller.Free((ushort*)__names_native__nativeSpan[__i0]);
                    }
                }

                global::System.Runtime.InteropServices.Marshalling.ArrayMarshaller<string, global::System.IntPtr>.Free(__names_native);
            }
        }

        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.SDK.IPropertyStorage.GetEnum(out global::DiaSharp.Storage.IEnumStatPropertyStorage enumerator)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.IPropertyStorage));
        bool __invokeSucceeded = default;
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out enumerator);
        void* __enumerator_native = default;
        int __retVal = default;
        try
        {
            {
                __retVal = ((delegate* unmanaged[MemberFunction]<void*, void**, int> )__vtable_native[5])(__this, &__enumerator_native);
            }

            __invokeSucceeded = true;
            global::System.GC.KeepAlive(this);
            // Unmarshal - Convert native data to managed data.
            enumerator = global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.Storage.IEnumStatPropertyStorage>.ConvertToManaged(__enumerator_native);
        }
        finally
        {
            if (__invokeSucceeded)
            {
                // CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
                global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.Storage.IEnumStatPropertyStorage>.Free(__enumerator_native);
            }
        }

        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.SDK.IPropertyStorage.ReadUint(uint id, out uint value)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.IPropertyStorage));
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out value);
        int __retVal;
        // Pin - Pin data in preparation for calling the P/Invoke.
        fixed (uint* __value_native = &value)
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, uint, uint*, int> )__vtable_native[6])(__this, id, __value_native);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.SDK.IPropertyStorage.ReadInt(out int value)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.IPropertyStorage));
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out value);
        int __retVal;
        // Pin - Pin data in preparation for calling the P/Invoke.
        fixed (int* __value_native = &value)
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, int*, int> )__vtable_native[7])(__this, __value_native);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.SDK.IPropertyStorage.ReadBool(uint id, out bool value)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.IPropertyStorage));
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out value);
        int __value_native;
        int __retVal;
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, uint, int*, int> )__vtable_native[8])(__this, id, &__value_native);
        }

        global::System.GC.KeepAlive(this);
        // Unmarshal - Convert native data to managed data.
        value = __value_native != 0;
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.SDK.IPropertyStorage.ReadUlong(uint id, out ulong value)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.IPropertyStorage));
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out value);
        int __retVal;
        // Pin - Pin data in preparation for calling the P/Invoke.
        fixed (ulong* __value_native = &value)
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, uint, ulong*, int> )__vtable_native[9])(__this, id, __value_native);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.SDK.IPropertyStorage.ReadBStr(uint id, out string value)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.IPropertyStorage));
        bool __invokeSucceeded = default;
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out value);
        ushort* __value_native = default;
        int __retVal = default;
        try
        {
            {
                __retVal = ((delegate* unmanaged[MemberFunction]<void*, uint, ushort**, int> )__vtable_native[10])(__this, id, &__value_native);
            }

            __invokeSucceeded = true;
            global::System.GC.KeepAlive(this);
            // Unmarshal - Convert native data to managed data.
            value = global::System.Runtime.InteropServices.Marshalling.BStrStringMarshaller.ConvertToManaged(__value_native);
        }
        finally
        {
            if (__invokeSucceeded)
            {
                // CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
                global::System.Runtime.InteropServices.Marshalling.BStrStringMarshaller.Free(__value_native);
            }
        }

        return __retVal;
    }
}

file unsafe partial interface InterfaceImplementation
{
    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_ReadMultiple(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, uint specifierCount, global::DiaSharp.Storage.PropertySpecifier* specifiers, void** __PropVariant_native__param)
    {
        global::DiaSharp.SDK.IPropertyStorage @this = default;
        ref void* __PropVariant_native = ref *__PropVariant_native__param;
        void* PropVariant = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.IPropertyStorage>(__this_native);
            __retVal = @this.ReadMultiple(specifierCount, specifiers, out PropVariant);
            // Marshal - Convert managed data to native data.
            __PropVariant_native = PropVariant;
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_ReadPropertyNames(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, uint propertyIDCount, uint* propertyIDs, global::System.IntPtr** __names_native__param)
    {
        global::DiaSharp.SDK.IPropertyStorage @this = default;
        ref global::System.IntPtr* __names_native = ref *__names_native__param;
        string[] names = default;
        int __retVal = default;
        // Setup - Perform required setup.
        int __names_native__numElements;
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out __names_native__numElements);
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.IPropertyStorage>(__this_native);
            __retVal = @this.ReadPropertyNames(propertyIDCount, propertyIDs, out names);
            // Marshal - Convert managed data to native data.
            __names_native = global::System.Runtime.InteropServices.Marshalling.ArrayMarshaller<string, global::System.IntPtr>.AllocateContainerForUnmanagedElements(names, out __names_native__numElements);
            {
                global::System.ReadOnlySpan<string> __names_native__managedSpan = global::System.Runtime.InteropServices.Marshalling.ArrayMarshaller<string, global::System.IntPtr>.GetManagedValuesSource(names);
                global::System.Span<global::System.IntPtr> __names_native__nativeSpan = global::System.Runtime.InteropServices.Marshalling.ArrayMarshaller<string, global::System.IntPtr>.GetUnmanagedValuesDestination(__names_native, __names_native__numElements);
                __names_native__nativeSpan.Clear();
                for (int __i0 = 0; __i0 < __names_native__managedSpan.Length; ++__i0)
                {
                    __names_native__nativeSpan[__i0] = (global::System.IntPtr)(ushort*)global::System.Runtime.InteropServices.Marshalling.BStrStringMarshaller.ConvertToUnmanaged(__names_native__managedSpan[__i0]);
                }
            }
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_GetEnum(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, void** __enumerator_native__param)
    {
        global::DiaSharp.SDK.IPropertyStorage @this = default;
        ref void* __enumerator_native = ref *__enumerator_native__param;
        global::DiaSharp.Storage.IEnumStatPropertyStorage enumerator = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.IPropertyStorage>(__this_native);
            __retVal = @this.GetEnum(out enumerator);
            // Marshal - Convert managed data to native data.
            __enumerator_native = (void*)global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.Storage.IEnumStatPropertyStorage>.ConvertToUnmanaged(enumerator);
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_ReadUint(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, uint id, uint* __value_native__param)
    {
        global::DiaSharp.SDK.IPropertyStorage @this = default;
        ref uint __value_native = ref *__value_native__param;
        uint value = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.IPropertyStorage>(__this_native);
            __retVal = @this.ReadUint(id, out value);
            // Marshal - Convert managed data to native data.
            __value_native = value;
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_ReadInt(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, int* __value_native__param)
    {
        global::DiaSharp.SDK.IPropertyStorage @this = default;
        ref int __value_native = ref *__value_native__param;
        int value = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.IPropertyStorage>(__this_native);
            __retVal = @this.ReadInt(out value);
            // Marshal - Convert managed data to native data.
            __value_native = value;
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_ReadBool(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, uint id, int* __value_native__param)
    {
        global::DiaSharp.SDK.IPropertyStorage @this = default;
        ref int __value_native = ref *__value_native__param;
        bool value = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.IPropertyStorage>(__this_native);
            __retVal = @this.ReadBool(id, out value);
            // Marshal - Convert managed data to native data.
            __value_native = (int)(value ? 1 : 0);
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_ReadUlong(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, uint id, ulong* __value_native__param)
    {
        global::DiaSharp.SDK.IPropertyStorage @this = default;
        ref ulong __value_native = ref *__value_native__param;
        ulong value = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.IPropertyStorage>(__this_native);
            __retVal = @this.ReadUlong(id, out value);
            // Marshal - Convert managed data to native data.
            __value_native = value;
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_ReadBStr(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, uint id, ushort** __value_native__param)
    {
        global::DiaSharp.SDK.IPropertyStorage @this = default;
        ref ushort* __value_native = ref *__value_native__param;
        string value = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.IPropertyStorage>(__this_native);
            __retVal = @this.ReadBStr(id, out value);
            // Marshal - Convert managed data to native data.
            __value_native = (ushort*)global::System.Runtime.InteropServices.Marshalling.BStrStringMarshaller.ConvertToUnmanaged(value);
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }
}

file unsafe partial interface InterfaceImplementation
{
    internal static void** CreateManagedVirtualFunctionTable()
    {
        void** vtable = (void**)global::System.Runtime.CompilerServices.RuntimeHelpers.AllocateTypeAssociatedMemory(typeof(global::DiaSharp.SDK.IPropertyStorage), sizeof(void*) * 11);
        {
            nint v0, v1, v2;
            global::System.Runtime.InteropServices.ComWrappers.GetIUnknownImpl(out v0, out v1, out v2);
            vtable[0] = (void*)v0;
            vtable[1] = (void*)v1;
            vtable[2] = (void*)v2;
        }

        {
            vtable[3] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, uint, global::DiaSharp.Storage.PropertySpecifier*, void**, int> )&ABI_ReadMultiple;
            vtable[4] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, uint, uint*, global::System.IntPtr**, int> )&ABI_ReadPropertyNames;
            vtable[5] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, void**, int> )&ABI_GetEnum;
            vtable[6] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, uint, uint*, int> )&ABI_ReadUint;
            vtable[7] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, int*, int> )&ABI_ReadInt;
            vtable[8] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, uint, int*, int> )&ABI_ReadBool;
            vtable[9] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, uint, ulong*, int> )&ABI_ReadUlong;
            vtable[10] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, uint, ushort**, int> )&ABI_ReadBStr;
        }

        return vtable;
    }
}

namespace DiaSharp.SDK
{
    [global::System.Runtime.InteropServices.Marshalling.IUnknownDerivedAttribute<InterfaceInformation, InterfaceImplementation>]
    public partial interface IPropertyStorage
    {
    }
}

namespace DiaSharp.SDK
{
    public partial interface IPropertyStorage
    {
    }
}