<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>

		<PackageId>DiaSharp</PackageId>

		<Description>High-performance C# wrapper for the Microsoft DIA SDK.</Description>
	</PropertyGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.DisableRuntimeMarshallingAttribute"/>
	</ItemGroup>

	<ItemGroup Label="Global Usings">
		<Using Include="System.Runtime.InteropServices.Marshalling" />
	</ItemGroup>

</Project>
