<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup> </PropertyGroup>

	<PropertyGroup Label="Nuget">
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	  
		<Title>DiaSharp</Title>
		<Authors>Red-K0</Authors>
	  
		<RepositoryUrl>https://github.com/Red-K0/DiaSharp/</RepositoryUrl>
		<RepositoryType>git</RepositoryType>

		<PackageReadmeFile>README.md</PackageReadmeFile>
	
	</PropertyGroup>

	<PropertyGroup Label="Versioning">
		<AssemblyVersion>$(Version)</AssemblyVersion>
		<PackageVersion>$(Version)</PackageVersion>
		<FileVersion>$(Version)</FileVersion>
		<Version>1.0.0</Version>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\README.md">
			<PackagePath>\</PackagePath>
			<Pack>True</Pack>
		</None>
	</ItemGroup>

	<ItemGroup Label="Global Usings">
		<Using Include="System.Reflection" />
		<Using Include="System.Runtime.InteropServices" />
		<Using Include="System.Runtime.InteropServices.Marshalling" />
	</ItemGroup>

</Project>
