// <auto-generated />
#pragma warning disable CS0612, CS0618
file unsafe class InterfaceInformation : System.Runtime.InteropServices.Marshalling.IIUnknownInterfaceType
{
	public static System.Guid Iid { get; } = new(new System.ReadOnlySpan<byte>(new byte[] { 221, 200, 64, 210, 15, 26, 110, 69, 128, 166, 79, 29, 6, 191, 93, 244 }));

	private static void** _vtable;
	public static void** ManagedVirtualMethodTable => _vtable != null ? _vtable : (_vtable = InterfaceImplementation.CreateManagedVirtualFunctionTable());
}

[System.Runtime.InteropServices.DynamicInterfaceCastableImplementationAttribute]
file unsafe partial interface InterfaceImplementation : DiaSharp.SDK.IDataSourceEx2
{
	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.IDataSourceEx2.FindNamedStreams(string name, DiaSharp.CodeView.NameSearchOptions searchOptions, out DiaSharp.SDK.Enumerators.IEnumNamedStreams streams)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.IDataSourceEx2));
		bool __invokeSucceeded = default;
		System.Runtime.CompilerServices.Unsafe.SkipInit(out streams);
		ushort* __name_native = default;
		void* __streams_native = default;
		int __retVal = default;
		// Setup - Perform required setup.
		scoped System.Runtime.InteropServices.Marshalling.BStrStringMarshaller.ManagedToUnmanagedIn __name_native__marshaller = new();
		try
		{
			// Marshal - Convert managed data to native data.
			__name_native__marshaller.FromManaged(name, stackalloc byte[System.Runtime.InteropServices.Marshalling.BStrStringMarshaller.ManagedToUnmanagedIn.BufferSize]);
			{
				// PinnedMarshal - Convert managed data to native data that requires the managed data to be pinned.
				__name_native = __name_native__marshaller.ToUnmanaged();
				__retVal = ((delegate* unmanaged[MemberFunction]<void*, ushort*, DiaSharp.CodeView.NameSearchOptions, void**, int> )__vtable_native[19])(__this, __name_native, searchOptions, &__streams_native);
			}

			__invokeSucceeded = true;
			System.GC.KeepAlive(this);
			// Unmarshal - Convert native data to managed data.
			streams = System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Enumerators.IEnumNamedStreams>.ConvertToManaged(__streams_native);
		}
		finally
		{
			if (__invokeSucceeded)
			{
				// CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
				System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Enumerators.IEnumNamedStreams>.Free(__streams_native);
			}

			// CleanupCallerAllocated - Perform cleanup of caller allocated resources.
			__name_native__marshaller.Free();
		}

		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.IDataSourceEx2.GetLastError(out string error)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.IDataSourceEx2));
		bool __invokeSucceeded = default;
		System.Runtime.CompilerServices.Unsafe.SkipInit(out error);
		ushort* __error_native = default;
		int __retVal = default;
		try
		{
			{
				__retVal = ((delegate* unmanaged[MemberFunction]<void*, ushort**, int> )__vtable_native[3])(__this, &__error_native);
			}

			__invokeSucceeded = true;
			System.GC.KeepAlive(this);
			// Unmarshal - Convert native data to managed data.
			error = System.Runtime.InteropServices.Marshalling.BStrStringMarshaller.ConvertToManaged(__error_native);
		}
		finally
		{
			if (__invokeSucceeded)
			{
				// CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
				System.Runtime.InteropServices.Marshalling.BStrStringMarshaller.Free(__error_native);
			}
		}

		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.IDataSourceEx2.LoadDataFromPdb(string pdbPath)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.IDataSourceEx2));
		int __retVal;
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (void* __pdbPath_native = &System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.GetPinnableReference(pdbPath))
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, ushort*, int> )__vtable_native[4])(__this, (ushort*)__pdbPath_native);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	unsafe int DiaSharp.SDK.IDataSourceEx2.LoadAndValidateDataFromPdb(string pdbPath, System.Guid* pdbSignature, uint signature, uint age)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.IDataSourceEx2));
		int __retVal;
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (void* __pdbPath_native = &System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.GetPinnableReference(pdbPath))
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, ushort*, System.Guid*, uint, uint, int> )__vtable_native[5])(__this, (ushort*)__pdbPath_native, pdbSignature, signature, age);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	unsafe int DiaSharp.SDK.IDataSourceEx2.LoadDataForExe(string exePath, string searchPath, void* callback)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.IDataSourceEx2));
		int __retVal;
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (void* __searchPath_native = &System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.GetPinnableReference(searchPath))
		fixed (void* __exePath_native = &System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.GetPinnableReference(exePath))
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, ushort*, ushort*, void*, int> )__vtable_native[6])(__this, (ushort*)__exePath_native, (ushort*)__searchPath_native, callback);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.IDataSourceEx2.LoadDataFromIStream(DiaSharp.Storage.IStream stream)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.IDataSourceEx2));
		void* __stream_native = default;
		int __retVal = default;
		try
		{
			// Marshal - Convert managed data to native data.
			__stream_native = (void*)System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.Storage.IStream>.ConvertToUnmanaged(stream);
			{
				__retVal = ((delegate* unmanaged[MemberFunction]<void*, void*, int> )__vtable_native[7])(__this, __stream_native);
			}

			System.GC.KeepAlive(this);
		}
		finally
		{
			// CleanupCallerAllocated - Perform cleanup of caller allocated resources.
			System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.Storage.IStream>.Free(__stream_native);
		}

		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.IDataSourceEx2.OpenSession(out DiaSharp.SDK.ISession session)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.IDataSourceEx2));
		bool __invokeSucceeded = default;
		System.Runtime.CompilerServices.Unsafe.SkipInit(out session);
		void* __session_native = default;
		int __retVal = default;
		try
		{
			{
				__retVal = ((delegate* unmanaged[MemberFunction]<void*, void**, int> )__vtable_native[8])(__this, &__session_native);
			}

			__invokeSucceeded = true;
			System.GC.KeepAlive(this);
			// Unmarshal - Convert native data to managed data.
			session = System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.ISession>.ConvertToManaged(__session_native);
		}
		finally
		{
			if (__invokeSucceeded)
			{
				// CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
				System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.ISession>.Free(__session_native);
			}
		}

		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	unsafe int DiaSharp.SDK.IDataSourceEx2.LoadDataFromCodeViewInfo(string executable, string searchPath, uint infoSize, byte* info, void* callback)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.IDataSourceEx2));
		int __retVal;
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (void* __searchPath_native = &System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.GetPinnableReference(searchPath))
		fixed (void* __executable_native = &System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.GetPinnableReference(executable))
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, ushort*, ushort*, uint, byte*, void*, int> )__vtable_native[9])(__this, (ushort*)__executable_native, (ushort*)__searchPath_native, infoSize, info, callback);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	unsafe int DiaSharp.SDK.IDataSourceEx2.LoadDataFromMiscInfo(string executable, string searchPath, uint exeTimestamp, uint debugTimestamp, uint exeSize, uint infoSize, byte* info, void* callback)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.IDataSourceEx2));
		int __retVal;
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (void* __searchPath_native = &System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.GetPinnableReference(searchPath))
		fixed (void* __executable_native = &System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.GetPinnableReference(executable))
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, ushort*, ushort*, uint, uint, uint, uint, byte*, void*, int> )__vtable_native[10])(__this, (ushort*)__executable_native, (ushort*)__searchPath_native, exeTimestamp, debugTimestamp, exeSize, infoSize, info, callback);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.IDataSourceEx2.LoadDataFromPdb(string pdbPath, bool prefetchPDB)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.IDataSourceEx2));
		int __prefetchPDB_native;
		int __retVal;
		// Marshal - Convert managed data to native data.
		__prefetchPDB_native = (int)(prefetchPDB ? 1 : 0);
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (void* __pdbPath_native = &System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.GetPinnableReference(pdbPath))
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, ushort*, int, int> )__vtable_native[11])(__this, (ushort*)__pdbPath_native, __prefetchPDB_native);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.IDataSourceEx2.LoadAndValidateDataFromPdb(string pdbPath, ref System.Guid pdbSignature, uint signature, uint age, bool prefetchPDB)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.IDataSourceEx2));
		int __prefetchPDB_native;
		int __retVal;
		// Marshal - Convert managed data to native data.
		__prefetchPDB_native = (int)(prefetchPDB ? 1 : 0);
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (System.Guid* __pdbSignature_native = &pdbSignature)
		fixed (void* __pdbPath_native = &System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.GetPinnableReference(pdbPath))
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, ushort*, System.Guid*, uint, uint, int, int> )__vtable_native[12])(__this, (ushort*)__pdbPath_native, __pdbSignature_native, signature, age, __prefetchPDB_native);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	unsafe int DiaSharp.SDK.IDataSourceEx2.LoadDataForExe(string executable, string searchPath, void* callback, bool prefetchPDB)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.IDataSourceEx2));
		int __prefetchPDB_native;
		int __retVal;
		// Marshal - Convert managed data to native data.
		__prefetchPDB_native = (int)(prefetchPDB ? 1 : 0);
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (void* __searchPath_native = &System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.GetPinnableReference(searchPath))
		fixed (void* __executable_native = &System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.GetPinnableReference(executable))
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, ushort*, ushort*, void*, int, int> )__vtable_native[13])(__this, (ushort*)__executable_native, (ushort*)__searchPath_native, callback, __prefetchPDB_native);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.IDataSourceEx2.LoadDataFromIStream(DiaSharp.Storage.IStream stream, bool prefetchPDB)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.IDataSourceEx2));
		void* __stream_native = default;
		int __prefetchPDB_native = default;
		int __retVal = default;
		try
		{
			// Marshal - Convert managed data to native data.
			__prefetchPDB_native = (int)(prefetchPDB ? 1 : 0);
			__stream_native = (void*)System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.Storage.IStream>.ConvertToUnmanaged(stream);
			{
				__retVal = ((delegate* unmanaged[MemberFunction]<void*, void*, int, int> )__vtable_native[14])(__this, __stream_native, __prefetchPDB_native);
			}

			System.GC.KeepAlive(this);
		}
		finally
		{
			// CleanupCallerAllocated - Perform cleanup of caller allocated resources.
			System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.Storage.IStream>.Free(__stream_native);
		}

		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.IDataSourceEx2.GetStreamSize(string stream, out ulong size)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.IDataSourceEx2));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out size);
		int __retVal;
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (ulong* __size_native = &size)
		fixed (void* __stream_native = &System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.GetPinnableReference(stream))
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, ushort*, ulong*, int> )__vtable_native[15])(__this, (ushort*)__stream_native, __size_native);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	unsafe int DiaSharp.SDK.IDataSourceEx2.GetStreamRawData(string stream, ulong byteOffset, ulong bufferSize, out ulong bytesWritten, byte* buffer)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.IDataSourceEx2));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out bytesWritten);
		int __retVal;
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (ulong* __bytesWritten_native = &bytesWritten)
		fixed (void* __stream_native = &System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.GetPinnableReference(stream))
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, ushort*, ulong, ulong, ulong*, byte*, int> )__vtable_native[16])(__this, (ushort*)__stream_native, byteOffset, bufferSize, __bytesWritten_native, buffer);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.IDataSourceEx2.SetMiniPdbErrorCallback(nint context, DiaSharp.SDK.Callbacks.MiniPdbErrorCallback callback)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.IDataSourceEx2));
		System.IntPtr __callback_native;
		int __retVal;
		// Marshal - Convert managed data to native data.
		__callback_native = callback != null ? System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(callback) : default;
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, nint, System.IntPtr, int> )__vtable_native[17])(__this, context, __callback_native);
		}

		// NotifyForSuccessfulInvoke - Keep alive any managed objects that need to stay alive across the call.
		System.GC.KeepAlive(callback);
		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.IDataSourceEx2.ValidatePdb(string pdbPath, ref System.Guid pdbSignature, uint signature, uint age, out bool valid)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.IDataSourceEx2));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out valid);
		int __valid_native;
		int __retVal;
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (System.Guid* __pdbSignature_native = &pdbSignature)
		fixed (void* __pdbPath_native = &System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.GetPinnableReference(pdbPath))
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, ushort*, System.Guid*, uint, uint, int*, int> )__vtable_native[18])(__this, (ushort*)__pdbPath_native, __pdbSignature_native, signature, age, &__valid_native);
		}

		System.GC.KeepAlive(this);
		// Unmarshal - Convert native data to managed data.
		valid = __valid_native != 0;
		return __retVal;
	}

	int DiaSharp.SDK.IDataSource.GetLastError(out string error) => throw new System.Diagnostics.UnreachableException();
	int DiaSharp.SDK.IDataSource.LoadDataFromPdb(string pdbPath) => throw new System.Diagnostics.UnreachableException();
	int DiaSharp.SDK.IDataSource.LoadAndValidateDataFromPdb(string pdbPath, System.Guid* pdbSignature, uint signature, uint age) => throw new System.Diagnostics.UnreachableException();
	int DiaSharp.SDK.IDataSource.LoadDataForExe(string exePath, string searchPath, void* callback) => throw new System.Diagnostics.UnreachableException();
	int DiaSharp.SDK.IDataSource.LoadDataFromIStream(DiaSharp.Storage.IStream stream) => throw new System.Diagnostics.UnreachableException();
	int DiaSharp.SDK.IDataSource.OpenSession(out DiaSharp.SDK.ISession session) => throw new System.Diagnostics.UnreachableException();
	int DiaSharp.SDK.IDataSource.LoadDataFromCodeViewInfo(string executable, string searchPath, uint infoSize, byte* info, void* callback) => throw new System.Diagnostics.UnreachableException();
	int DiaSharp.SDK.IDataSource.LoadDataFromMiscInfo(string executable, string searchPath, uint exeTimestamp, uint debugTimestamp, uint exeSize, uint infoSize, byte* info, void* callback) => throw new System.Diagnostics.UnreachableException();
	int DiaSharp.SDK.IDataSourceEx.LoadDataFromPdb(string pdbPath, bool prefetchPDB) => throw new System.Diagnostics.UnreachableException();
	int DiaSharp.SDK.IDataSourceEx.LoadAndValidateDataFromPdb(string pdbPath, ref System.Guid pdbSignature, uint signature, uint age, bool prefetchPDB) => throw new System.Diagnostics.UnreachableException();
	int DiaSharp.SDK.IDataSourceEx.LoadDataForExe(string executable, string searchPath, void* callback, bool prefetchPDB) => throw new System.Diagnostics.UnreachableException();
	int DiaSharp.SDK.IDataSourceEx.LoadDataFromIStream(DiaSharp.Storage.IStream stream, bool prefetchPDB) => throw new System.Diagnostics.UnreachableException();
	int DiaSharp.SDK.IDataSourceEx.GetStreamSize(string stream, out ulong size) => throw new System.Diagnostics.UnreachableException();
	int DiaSharp.SDK.IDataSourceEx.GetStreamRawData(string stream, ulong byteOffset, ulong bufferSize, out ulong bytesWritten, byte* buffer) => throw new System.Diagnostics.UnreachableException();
	int DiaSharp.SDK.IDataSourceEx.SetMiniPdbErrorCallback(nint context, DiaSharp.SDK.Callbacks.MiniPdbErrorCallback callback) => throw new System.Diagnostics.UnreachableException();
	int DiaSharp.SDK.IDataSourceEx.ValidatePdb(string pdbPath, ref System.Guid pdbSignature, uint signature, uint age, out bool valid) => throw new System.Diagnostics.UnreachableException();

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_FindNamedStreams(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, ushort* __name_native, DiaSharp.CodeView.NameSearchOptions searchOptions, void** __streams_native__param)
	{
		DiaSharp.SDK.IDataSourceEx2 @this = default;
		string name = default;
		ref void* __streams_native = ref *__streams_native__param;
		DiaSharp.SDK.Enumerators.IEnumNamedStreams streams = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			name = System.Runtime.InteropServices.Marshalling.BStrStringMarshaller.ConvertToManaged(__name_native);
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.IDataSourceEx2>(__this_native);
			__retVal = @this.FindNamedStreams(name, searchOptions, out streams);
			// Marshal - Convert managed data to native data.
			__streams_native = (void*)System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Enumerators.IEnumNamedStreams>.ConvertToUnmanaged(streams);
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	internal static void** CreateManagedVirtualFunctionTable()
	{
		void** vtable = (void**)System.Runtime.CompilerServices.RuntimeHelpers.AllocateTypeAssociatedMemory(typeof(DiaSharp.SDK.IDataSourceEx2), sizeof(void*) * 20);
		{
			System.Runtime.InteropServices.NativeMemory.Copy(System.Runtime.InteropServices.Marshalling.StrategyBasedComWrappers.DefaultIUnknownInterfaceDetailsStrategy.GetIUnknownDerivedDetails(typeof(DiaSharp.SDK.IDataSourceEx).TypeHandle).ManagedVirtualMethodTable, vtable, (nuint)(sizeof(void*) * 19));
		}

		{
			vtable[19] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, ushort*, DiaSharp.CodeView.NameSearchOptions, void**, int> )&ABI_FindNamedStreams;
		}

		return vtable;
	}
}

namespace DiaSharp.SDK
{
	[System.Runtime.InteropServices.Marshalling.IUnknownDerivedAttribute<InterfaceInformation, InterfaceImplementation>]
	public partial interface IDataSourceEx2
	{
		[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
		[System.Runtime.InteropServices.PreserveSigAttribute()]
		new int GetLastError(out string error) => ((DiaSharp.SDK.IDataSource)this).GetLastError(out error);

		[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
		[System.Runtime.InteropServices.PreserveSigAttribute()]
		new int LoadDataFromPdb(string pdbPath) => ((DiaSharp.SDK.IDataSource)this).LoadDataFromPdb(pdbPath);

		[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
		[System.Runtime.InteropServices.PreserveSigAttribute()]
		new unsafe int LoadAndValidateDataFromPdb(string pdbPath, System.Guid* pdbSignature, uint signature, uint age) => ((DiaSharp.SDK.IDataSource)this).LoadAndValidateDataFromPdb(pdbPath, pdbSignature, signature, age);

		[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
		[System.Runtime.InteropServices.PreserveSigAttribute()]
		new unsafe int LoadDataForExe(string exePath, string searchPath, void* callback) => ((DiaSharp.SDK.IDataSource)this).LoadDataForExe(exePath, searchPath, callback);

		[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
		[System.Runtime.InteropServices.PreserveSigAttribute()]
		new int LoadDataFromIStream(DiaSharp.Storage.IStream stream) => ((DiaSharp.SDK.IDataSource)this).LoadDataFromIStream(stream);

		[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
		[System.Runtime.InteropServices.PreserveSigAttribute()]
		new int OpenSession(out DiaSharp.SDK.ISession session) => ((DiaSharp.SDK.IDataSource)this).OpenSession(out session);

		[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
		[System.Runtime.InteropServices.PreserveSigAttribute()]
		new unsafe int LoadDataFromCodeViewInfo(string executable, string searchPath, uint infoSize, byte* info, void* callback) => ((DiaSharp.SDK.IDataSource)this).LoadDataFromCodeViewInfo(executable, searchPath, infoSize, info, callback);

		[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
		[System.Runtime.InteropServices.PreserveSigAttribute()]
		new unsafe int LoadDataFromMiscInfo(string executable, string searchPath, uint exeTimestamp, uint debugTimestamp, uint exeSize, uint infoSize, byte* info, void* callback) => ((DiaSharp.SDK.IDataSource)this).LoadDataFromMiscInfo(executable, searchPath, exeTimestamp, debugTimestamp, exeSize, infoSize, info, callback);

		[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
		[System.Runtime.InteropServices.PreserveSigAttribute()]
		new int LoadDataFromPdb(string pdbPath, bool prefetchPDB) => ((DiaSharp.SDK.IDataSourceEx)this).LoadDataFromPdb(pdbPath, prefetchPDB);

		[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
		[System.Runtime.InteropServices.PreserveSigAttribute()]
		new int LoadAndValidateDataFromPdb(string pdbPath, ref System.Guid pdbSignature, uint signature, uint age, bool prefetchPDB) => ((DiaSharp.SDK.IDataSourceEx)this).LoadAndValidateDataFromPdb(pdbPath, ref pdbSignature, signature, age, prefetchPDB);

		[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
		[System.Runtime.InteropServices.PreserveSigAttribute()]
		new unsafe int LoadDataForExe(string executable, string searchPath, void* callback, bool prefetchPDB) => ((DiaSharp.SDK.IDataSourceEx)this).LoadDataForExe(executable, searchPath, callback, prefetchPDB);

		[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
		[System.Runtime.InteropServices.PreserveSigAttribute()]
		new int LoadDataFromIStream(DiaSharp.Storage.IStream stream, bool prefetchPDB) => ((DiaSharp.SDK.IDataSourceEx)this).LoadDataFromIStream(stream, prefetchPDB);

		[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
		[System.Runtime.InteropServices.PreserveSigAttribute()]
		new int GetStreamSize(string stream, out ulong size) => ((DiaSharp.SDK.IDataSourceEx)this).GetStreamSize(stream, out size);

		[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
		[System.Runtime.InteropServices.PreserveSigAttribute()]
		new unsafe int GetStreamRawData(string stream, ulong byteOffset, ulong bufferSize, out ulong bytesWritten, byte* buffer) => ((DiaSharp.SDK.IDataSourceEx)this).GetStreamRawData(stream, byteOffset, bufferSize, out bytesWritten, buffer);

		[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
		[System.Runtime.InteropServices.PreserveSigAttribute()]
		new int SetMiniPdbErrorCallback(nint context, DiaSharp.SDK.Callbacks.MiniPdbErrorCallback callback) => ((DiaSharp.SDK.IDataSourceEx)this).SetMiniPdbErrorCallback(context, callback);

		[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
		[System.Runtime.InteropServices.PreserveSigAttribute()]
		new int ValidatePdb(string pdbPath, ref System.Guid pdbSignature, uint signature, uint age, out bool valid) => ((DiaSharp.SDK.IDataSourceEx)this).ValidatePdb(pdbPath, ref pdbSignature, signature, age, out valid);
	}
}