// <auto-generated />
#pragma warning disable CS0612, CS0618
file unsafe class InterfaceInformation : System.Runtime.InteropServices.Marshalling.IIUnknownInterfaceType
{
	public static System.Guid Iid { get; } = new(new System.ReadOnlySpan<byte>(new byte[] { 14, 182, 244, 12, 177, 53, 108, 76, 189, 216, 133, 75, 156, 142, 56, 87 }));

	private static void** _vtable;
	public static void** ManagedVirtualMethodTable => _vtable != null ? _vtable : (_vtable = InterfaceImplementation.CreateManagedVirtualFunctionTable());
}

[System.Runtime.InteropServices.DynamicInterfaceCastableImplementationAttribute]
file unsafe partial interface InterfaceImplementation : DiaSharp.SDK.ISectionContrib
{
	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.ISectionContrib.GetCompiland(out DiaSharp.SDK.Symbols.ISymbol compiland)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.ISectionContrib));
		bool __invokeSucceeded = default;
		System.Runtime.CompilerServices.Unsafe.SkipInit(out compiland);
		void* __compiland_native = default;
		int __retVal = default;
		try
		{
			{
				__retVal = ((delegate* unmanaged[MemberFunction]<void*, void**, int> )__vtable_native[3])(__this, &__compiland_native);
			}

			__invokeSucceeded = true;
			System.GC.KeepAlive(this);
			// Unmarshal - Convert native data to managed data.
			compiland = System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Symbols.ISymbol>.ConvertToManaged(__compiland_native);
		}
		finally
		{
			if (__invokeSucceeded)
			{
				// CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
				System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Symbols.ISymbol>.Free(__compiland_native);
			}
		}

		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.ISectionContrib.GetAddressSection(out uint section)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.ISectionContrib));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out section);
		int __retVal;
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (uint* __section_native = &section)
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, uint*, int> )__vtable_native[4])(__this, __section_native);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.ISectionContrib.GetAddressOffset(out uint offset)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.ISectionContrib));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out offset);
		int __retVal;
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (uint* __offset_native = &offset)
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, uint*, int> )__vtable_native[5])(__this, __offset_native);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.ISectionContrib.GetRelativeVirtualAddress(out uint rva)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.ISectionContrib));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out rva);
		int __retVal;
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (uint* __rva_native = &rva)
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, uint*, int> )__vtable_native[6])(__this, __rva_native);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.ISectionContrib.GetVirtualAddress(out ulong va)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.ISectionContrib));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out va);
		int __retVal;
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (ulong* __va_native = &va)
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, ulong*, int> )__vtable_native[7])(__this, __va_native);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.ISectionContrib.GetLength(out uint length)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.ISectionContrib));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out length);
		int __retVal;
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (uint* __length_native = &length)
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, uint*, int> )__vtable_native[8])(__this, __length_native);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.ISectionContrib.GetNotPaged(out bool value)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.ISectionContrib));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out value);
		int __value_native;
		int __retVal;
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, int*, int> )__vtable_native[9])(__this, &__value_native);
		}

		System.GC.KeepAlive(this);
		// Unmarshal - Convert native data to managed data.
		value = __value_native != 0;
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.ISectionContrib.GetNoPad(out bool value)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.ISectionContrib));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out value);
		int __value_native;
		int __retVal;
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, int*, int> )__vtable_native[10])(__this, &__value_native);
		}

		System.GC.KeepAlive(this);
		// Unmarshal - Convert native data to managed data.
		value = __value_native != 0;
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.ISectionContrib.GetHasCode(out bool value)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.ISectionContrib));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out value);
		int __value_native;
		int __retVal;
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, int*, int> )__vtable_native[11])(__this, &__value_native);
		}

		System.GC.KeepAlive(this);
		// Unmarshal - Convert native data to managed data.
		value = __value_native != 0;
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.ISectionContrib.GetHasInitializedData(out bool value)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.ISectionContrib));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out value);
		int __value_native;
		int __retVal;
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, int*, int> )__vtable_native[12])(__this, &__value_native);
		}

		System.GC.KeepAlive(this);
		// Unmarshal - Convert native data to managed data.
		value = __value_native != 0;
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.ISectionContrib.GetHasUninitializedData(out bool value)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.ISectionContrib));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out value);
		int __value_native;
		int __retVal;
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, int*, int> )__vtable_native[13])(__this, &__value_native);
		}

		System.GC.KeepAlive(this);
		// Unmarshal - Convert native data to managed data.
		value = __value_native != 0;
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.ISectionContrib.GetIsInformational(out bool value)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.ISectionContrib));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out value);
		int __value_native;
		int __retVal;
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, int*, int> )__vtable_native[14])(__this, &__value_native);
		}

		System.GC.KeepAlive(this);
		// Unmarshal - Convert native data to managed data.
		value = __value_native != 0;
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.ISectionContrib.GetIsRemoved(out bool value)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.ISectionContrib));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out value);
		int __value_native;
		int __retVal;
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, int*, int> )__vtable_native[15])(__this, &__value_native);
		}

		System.GC.KeepAlive(this);
		// Unmarshal - Convert native data to managed data.
		value = __value_native != 0;
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.ISectionContrib.GetIsCOMDAT(out bool value)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.ISectionContrib));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out value);
		int __value_native;
		int __retVal;
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, int*, int> )__vtable_native[16])(__this, &__value_native);
		}

		System.GC.KeepAlive(this);
		// Unmarshal - Convert native data to managed data.
		value = __value_native != 0;
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.ISectionContrib.GetIsDiscardable(out bool value)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.ISectionContrib));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out value);
		int __value_native;
		int __retVal;
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, int*, int> )__vtable_native[17])(__this, &__value_native);
		}

		System.GC.KeepAlive(this);
		// Unmarshal - Convert native data to managed data.
		value = __value_native != 0;
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.ISectionContrib.GetNotCached(out bool value)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.ISectionContrib));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out value);
		int __value_native;
		int __retVal;
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, int*, int> )__vtable_native[18])(__this, &__value_native);
		}

		System.GC.KeepAlive(this);
		// Unmarshal - Convert native data to managed data.
		value = __value_native != 0;
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.ISectionContrib.GetIsShareable(out bool value)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.ISectionContrib));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out value);
		int __value_native;
		int __retVal;
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, int*, int> )__vtable_native[19])(__this, &__value_native);
		}

		System.GC.KeepAlive(this);
		// Unmarshal - Convert native data to managed data.
		value = __value_native != 0;
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.ISectionContrib.GetIsExecutable(out bool value)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.ISectionContrib));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out value);
		int __value_native;
		int __retVal;
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, int*, int> )__vtable_native[20])(__this, &__value_native);
		}

		System.GC.KeepAlive(this);
		// Unmarshal - Convert native data to managed data.
		value = __value_native != 0;
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.ISectionContrib.GetIsReadable(out bool value)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.ISectionContrib));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out value);
		int __value_native;
		int __retVal;
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, int*, int> )__vtable_native[21])(__this, &__value_native);
		}

		System.GC.KeepAlive(this);
		// Unmarshal - Convert native data to managed data.
		value = __value_native != 0;
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.ISectionContrib.GetIsWriteable(out bool value)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.ISectionContrib));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out value);
		int __value_native;
		int __retVal;
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, int*, int> )__vtable_native[22])(__this, &__value_native);
		}

		System.GC.KeepAlive(this);
		// Unmarshal - Convert native data to managed data.
		value = __value_native != 0;
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.ISectionContrib.GetDataCRC(out uint crc)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.ISectionContrib));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out crc);
		int __retVal;
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (uint* __crc_native = &crc)
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, uint*, int> )__vtable_native[23])(__this, __crc_native);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.ISectionContrib.GetRelocationsCRC(out uint crc)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.ISectionContrib));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out crc);
		int __retVal;
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (uint* __crc_native = &crc)
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, uint*, int> )__vtable_native[24])(__this, __crc_native);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.ISectionContrib.GetCompilandID(out uint ID)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.ISectionContrib));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out ID);
		int __retVal;
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (uint* __ID_native = &ID)
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, uint*, int> )__vtable_native[25])(__this, __ID_native);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.ISectionContrib.GetHas16BitCode(out bool value)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.ISectionContrib));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out value);
		int __value_native;
		int __retVal;
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, int*, int> )__vtable_native[26])(__this, &__value_native);
		}

		System.GC.KeepAlive(this);
		// Unmarshal - Convert native data to managed data.
		value = __value_native != 0;
		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetCompiland(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, void** __compiland_native__param)
	{
		DiaSharp.SDK.ISectionContrib @this = default;
		ref void* __compiland_native = ref *__compiland_native__param;
		DiaSharp.SDK.Symbols.ISymbol compiland = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.ISectionContrib>(__this_native);
			__retVal = @this.GetCompiland(out compiland);
			// Marshal - Convert managed data to native data.
			__compiland_native = (void*)System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Symbols.ISymbol>.ConvertToUnmanaged(compiland);
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetAddressSection(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, uint* __section_native__param)
	{
		DiaSharp.SDK.ISectionContrib @this = default;
		ref uint __section_native = ref *__section_native__param;
		uint section = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.ISectionContrib>(__this_native);
			__retVal = @this.GetAddressSection(out section);
			// Marshal - Convert managed data to native data.
			__section_native = section;
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetAddressOffset(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, uint* __offset_native__param)
	{
		DiaSharp.SDK.ISectionContrib @this = default;
		ref uint __offset_native = ref *__offset_native__param;
		uint offset = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.ISectionContrib>(__this_native);
			__retVal = @this.GetAddressOffset(out offset);
			// Marshal - Convert managed data to native data.
			__offset_native = offset;
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetRelativeVirtualAddress(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, uint* __rva_native__param)
	{
		DiaSharp.SDK.ISectionContrib @this = default;
		ref uint __rva_native = ref *__rva_native__param;
		uint rva = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.ISectionContrib>(__this_native);
			__retVal = @this.GetRelativeVirtualAddress(out rva);
			// Marshal - Convert managed data to native data.
			__rva_native = rva;
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetVirtualAddress(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, ulong* __va_native__param)
	{
		DiaSharp.SDK.ISectionContrib @this = default;
		ref ulong __va_native = ref *__va_native__param;
		ulong va = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.ISectionContrib>(__this_native);
			__retVal = @this.GetVirtualAddress(out va);
			// Marshal - Convert managed data to native data.
			__va_native = va;
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetLength(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, uint* __length_native__param)
	{
		DiaSharp.SDK.ISectionContrib @this = default;
		ref uint __length_native = ref *__length_native__param;
		uint length = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.ISectionContrib>(__this_native);
			__retVal = @this.GetLength(out length);
			// Marshal - Convert managed data to native data.
			__length_native = length;
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetNotPaged(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, int* __value_native__param)
	{
		DiaSharp.SDK.ISectionContrib @this = default;
		ref int __value_native = ref *__value_native__param;
		bool value = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.ISectionContrib>(__this_native);
			__retVal = @this.GetNotPaged(out value);
			// Marshal - Convert managed data to native data.
			__value_native = (int)(value ? 1 : 0);
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetNoPad(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, int* __value_native__param)
	{
		DiaSharp.SDK.ISectionContrib @this = default;
		ref int __value_native = ref *__value_native__param;
		bool value = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.ISectionContrib>(__this_native);
			__retVal = @this.GetNoPad(out value);
			// Marshal - Convert managed data to native data.
			__value_native = (int)(value ? 1 : 0);
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetHasCode(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, int* __value_native__param)
	{
		DiaSharp.SDK.ISectionContrib @this = default;
		ref int __value_native = ref *__value_native__param;
		bool value = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.ISectionContrib>(__this_native);
			__retVal = @this.GetHasCode(out value);
			// Marshal - Convert managed data to native data.
			__value_native = (int)(value ? 1 : 0);
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetHasInitializedData(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, int* __value_native__param)
	{
		DiaSharp.SDK.ISectionContrib @this = default;
		ref int __value_native = ref *__value_native__param;
		bool value = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.ISectionContrib>(__this_native);
			__retVal = @this.GetHasInitializedData(out value);
			// Marshal - Convert managed data to native data.
			__value_native = (int)(value ? 1 : 0);
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetHasUninitializedData(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, int* __value_native__param)
	{
		DiaSharp.SDK.ISectionContrib @this = default;
		ref int __value_native = ref *__value_native__param;
		bool value = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.ISectionContrib>(__this_native);
			__retVal = @this.GetHasUninitializedData(out value);
			// Marshal - Convert managed data to native data.
			__value_native = (int)(value ? 1 : 0);
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetIsInformational(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, int* __value_native__param)
	{
		DiaSharp.SDK.ISectionContrib @this = default;
		ref int __value_native = ref *__value_native__param;
		bool value = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.ISectionContrib>(__this_native);
			__retVal = @this.GetIsInformational(out value);
			// Marshal - Convert managed data to native data.
			__value_native = (int)(value ? 1 : 0);
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetIsRemoved(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, int* __value_native__param)
	{
		DiaSharp.SDK.ISectionContrib @this = default;
		ref int __value_native = ref *__value_native__param;
		bool value = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.ISectionContrib>(__this_native);
			__retVal = @this.GetIsRemoved(out value);
			// Marshal - Convert managed data to native data.
			__value_native = (int)(value ? 1 : 0);
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetIsCOMDAT(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, int* __value_native__param)
	{
		DiaSharp.SDK.ISectionContrib @this = default;
		ref int __value_native = ref *__value_native__param;
		bool value = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.ISectionContrib>(__this_native);
			__retVal = @this.GetIsCOMDAT(out value);
			// Marshal - Convert managed data to native data.
			__value_native = (int)(value ? 1 : 0);
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetIsDiscardable(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, int* __value_native__param)
	{
		DiaSharp.SDK.ISectionContrib @this = default;
		ref int __value_native = ref *__value_native__param;
		bool value = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.ISectionContrib>(__this_native);
			__retVal = @this.GetIsDiscardable(out value);
			// Marshal - Convert managed data to native data.
			__value_native = (int)(value ? 1 : 0);
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetNotCached(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, int* __value_native__param)
	{
		DiaSharp.SDK.ISectionContrib @this = default;
		ref int __value_native = ref *__value_native__param;
		bool value = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.ISectionContrib>(__this_native);
			__retVal = @this.GetNotCached(out value);
			// Marshal - Convert managed data to native data.
			__value_native = (int)(value ? 1 : 0);
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetIsShareable(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, int* __value_native__param)
	{
		DiaSharp.SDK.ISectionContrib @this = default;
		ref int __value_native = ref *__value_native__param;
		bool value = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.ISectionContrib>(__this_native);
			__retVal = @this.GetIsShareable(out value);
			// Marshal - Convert managed data to native data.
			__value_native = (int)(value ? 1 : 0);
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetIsExecutable(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, int* __value_native__param)
	{
		DiaSharp.SDK.ISectionContrib @this = default;
		ref int __value_native = ref *__value_native__param;
		bool value = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.ISectionContrib>(__this_native);
			__retVal = @this.GetIsExecutable(out value);
			// Marshal - Convert managed data to native data.
			__value_native = (int)(value ? 1 : 0);
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetIsReadable(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, int* __value_native__param)
	{
		DiaSharp.SDK.ISectionContrib @this = default;
		ref int __value_native = ref *__value_native__param;
		bool value = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.ISectionContrib>(__this_native);
			__retVal = @this.GetIsReadable(out value);
			// Marshal - Convert managed data to native data.
			__value_native = (int)(value ? 1 : 0);
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetIsWriteable(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, int* __value_native__param)
	{
		DiaSharp.SDK.ISectionContrib @this = default;
		ref int __value_native = ref *__value_native__param;
		bool value = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.ISectionContrib>(__this_native);
			__retVal = @this.GetIsWriteable(out value);
			// Marshal - Convert managed data to native data.
			__value_native = (int)(value ? 1 : 0);
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetDataCRC(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, uint* __crc_native__param)
	{
		DiaSharp.SDK.ISectionContrib @this = default;
		ref uint __crc_native = ref *__crc_native__param;
		uint crc = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.ISectionContrib>(__this_native);
			__retVal = @this.GetDataCRC(out crc);
			// Marshal - Convert managed data to native data.
			__crc_native = crc;
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetRelocationsCRC(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, uint* __crc_native__param)
	{
		DiaSharp.SDK.ISectionContrib @this = default;
		ref uint __crc_native = ref *__crc_native__param;
		uint crc = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.ISectionContrib>(__this_native);
			__retVal = @this.GetRelocationsCRC(out crc);
			// Marshal - Convert managed data to native data.
			__crc_native = crc;
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetCompilandID(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, uint* __ID_native__param)
	{
		DiaSharp.SDK.ISectionContrib @this = default;
		ref uint __ID_native = ref *__ID_native__param;
		uint ID = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.ISectionContrib>(__this_native);
			__retVal = @this.GetCompilandID(out ID);
			// Marshal - Convert managed data to native data.
			__ID_native = ID;
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetHas16BitCode(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, int* __value_native__param)
	{
		DiaSharp.SDK.ISectionContrib @this = default;
		ref int __value_native = ref *__value_native__param;
		bool value = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.ISectionContrib>(__this_native);
			__retVal = @this.GetHas16BitCode(out value);
			// Marshal - Convert managed data to native data.
			__value_native = (int)(value ? 1 : 0);
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	internal static void** CreateManagedVirtualFunctionTable()
	{
		void** vtable = (void**)System.Runtime.CompilerServices.RuntimeHelpers.AllocateTypeAssociatedMemory(typeof(DiaSharp.SDK.ISectionContrib), sizeof(void*) * 27);
		{
			nint v0, v1, v2;
			System.Runtime.InteropServices.ComWrappers.GetIUnknownImpl(out v0, out v1, out v2);
			vtable[0] = (void*)v0;
			vtable[1] = (void*)v1;
			vtable[2] = (void*)v2;
		}

		{
			vtable[3] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, void**, int> )&ABI_GetCompiland;
			vtable[4] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, uint*, int> )&ABI_GetAddressSection;
			vtable[5] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, uint*, int> )&ABI_GetAddressOffset;
			vtable[6] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, uint*, int> )&ABI_GetRelativeVirtualAddress;
			vtable[7] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, ulong*, int> )&ABI_GetVirtualAddress;
			vtable[8] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, uint*, int> )&ABI_GetLength;
			vtable[9] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, int*, int> )&ABI_GetNotPaged;
			vtable[10] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, int*, int> )&ABI_GetNoPad;
			vtable[11] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, int*, int> )&ABI_GetHasCode;
			vtable[12] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, int*, int> )&ABI_GetHasInitializedData;
			vtable[13] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, int*, int> )&ABI_GetHasUninitializedData;
			vtable[14] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, int*, int> )&ABI_GetIsInformational;
			vtable[15] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, int*, int> )&ABI_GetIsRemoved;
			vtable[16] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, int*, int> )&ABI_GetIsCOMDAT;
			vtable[17] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, int*, int> )&ABI_GetIsDiscardable;
			vtable[18] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, int*, int> )&ABI_GetNotCached;
			vtable[19] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, int*, int> )&ABI_GetIsShareable;
			vtable[20] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, int*, int> )&ABI_GetIsExecutable;
			vtable[21] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, int*, int> )&ABI_GetIsReadable;
			vtable[22] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, int*, int> )&ABI_GetIsWriteable;
			vtable[23] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, uint*, int> )&ABI_GetDataCRC;
			vtable[24] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, uint*, int> )&ABI_GetRelocationsCRC;
			vtable[25] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, uint*, int> )&ABI_GetCompilandID;
			vtable[26] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, int*, int> )&ABI_GetHas16BitCode;
		}

		return vtable;
	}
}

namespace DiaSharp.SDK
{
	[System.Runtime.InteropServices.Marshalling.IUnknownDerivedAttribute<InterfaceInformation, InterfaceImplementation>]
	public partial interface ISectionContrib
	{
	}
}