// <auto-generated />
#pragma warning disable CS0612, CS0618
file unsafe class InterfaceInformation : System.Runtime.InteropServices.Marshalling.IIUnknownInterfaceType
{
	public static System.Guid Iid { get; } = new(new System.ReadOnlySpan<byte>(new byte[] { 81, 129, 109, 19, 231, 173, 4, 71, 175, 19, 50, 64, 128, 118, 46, 143 }));

	private static void** _vtable;
	public static void** ManagedVirtualMethodTable => _vtable != null ? _vtable : (_vtable = InterfaceImplementation.CreateManagedVirtualFunctionTable());
}

[System.Runtime.InteropServices.DynamicInterfaceCastableImplementationAttribute]
file unsafe partial interface InterfaceImplementation : DiaSharp.SDK.Enumerators.IEnumSourceLink2
{
	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.Enumerators.IEnumSourceLink2.SizeOfNext(out ulong size)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.Enumerators.IEnumSourceLink2));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out size);
		int __retVal;
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (ulong* __size_native = &size)
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, ulong*, int> )__vtable_native[9])(__this, __size_native);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	unsafe int DiaSharp.SDK.Enumerators.IEnumSourceLink2.GetNext(ulong bufferSize, out ulong bytesWritten, byte* buffer)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.Enumerators.IEnumSourceLink2));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out bytesWritten);
		int __retVal;
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (ulong* __bytesWritten_native = &bytesWritten)
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, ulong, ulong*, byte*, int> )__vtable_native[10])(__this, bufferSize, __bytesWritten_native, buffer);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.Enumerators.IEnumSourceLink2.Count(out uint count)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.Enumerators.IEnumSourceLink2));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out count);
		int __retVal;
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (uint* __count_native = &count)
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, uint*, int> )__vtable_native[3])(__this, __count_native);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.Enumerators.IEnumSourceLink2.SizeOfNext(out uint size)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.Enumerators.IEnumSourceLink2));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out size);
		int __retVal;
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (uint* __size_native = &size)
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, uint*, int> )__vtable_native[4])(__this, __size_native);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	unsafe int DiaSharp.SDK.Enumerators.IEnumSourceLink2.GetNext(uint bufferSize, out uint bytesWritten, byte* buffer)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.Enumerators.IEnumSourceLink2));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out bytesWritten);
		int __retVal;
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (uint* __bytesWritten_native = &bytesWritten)
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, uint, uint*, byte*, int> )__vtable_native[5])(__this, bufferSize, __bytesWritten_native, buffer);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.Enumerators.IEnumSourceLink2.Skip(uint byteCount)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.Enumerators.IEnumSourceLink2));
		int __retVal;
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, uint, int> )__vtable_native[6])(__this, byteCount);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.Enumerators.IEnumSourceLink2.Reset()
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.Enumerators.IEnumSourceLink2));
		int __retVal;
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, int> )__vtable_native[7])(__this);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.Enumerators.IEnumSourceLink2.Clone(out DiaSharp.SDK.Enumerators.IEnumSourceLink enumerator)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.Enumerators.IEnumSourceLink2));
		bool __invokeSucceeded = default;
		System.Runtime.CompilerServices.Unsafe.SkipInit(out enumerator);
		void* __enumerator_native = default;
		int __retVal = default;
		try
		{
			{
				__retVal = ((delegate* unmanaged[MemberFunction]<void*, void**, int> )__vtable_native[8])(__this, &__enumerator_native);
			}

			__invokeSucceeded = true;
			System.GC.KeepAlive(this);
			// Unmarshal - Convert native data to managed data.
			enumerator = System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Enumerators.IEnumSourceLink>.ConvertToManaged(__enumerator_native);
		}
		finally
		{
			if (__invokeSucceeded)
			{
				// CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
				System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Enumerators.IEnumSourceLink>.Free(__enumerator_native);
			}
		}

		return __retVal;
	}

	int DiaSharp.SDK.Enumerators.IEnumSourceLink.Count(out uint count) => throw new System.Diagnostics.UnreachableException();
	int DiaSharp.SDK.Enumerators.IEnumSourceLink.SizeOfNext(out uint size) => throw new System.Diagnostics.UnreachableException();
	int DiaSharp.SDK.Enumerators.IEnumSourceLink.GetNext(uint bufferSize, out uint bytesWritten, byte* buffer) => throw new System.Diagnostics.UnreachableException();
	int DiaSharp.SDK.Enumerators.IEnumSourceLink.Skip(uint byteCount) => throw new System.Diagnostics.UnreachableException();
	int DiaSharp.SDK.Enumerators.IEnumSourceLink.Reset() => throw new System.Diagnostics.UnreachableException();
	int DiaSharp.SDK.Enumerators.IEnumSourceLink.Clone(out DiaSharp.SDK.Enumerators.IEnumSourceLink enumerator) => throw new System.Diagnostics.UnreachableException();

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_SizeOfNext(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, ulong* __size_native__param)
	{
		DiaSharp.SDK.Enumerators.IEnumSourceLink2 @this = default;
		ref ulong __size_native = ref *__size_native__param;
		ulong size = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.Enumerators.IEnumSourceLink2>(__this_native);
			__retVal = @this.SizeOfNext(out size);
			// Marshal - Convert managed data to native data.
			__size_native = size;
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetNext(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, ulong bufferSize, ulong* __bytesWritten_native__param, byte* buffer)
	{
		DiaSharp.SDK.Enumerators.IEnumSourceLink2 @this = default;
		ref ulong __bytesWritten_native = ref *__bytesWritten_native__param;
		ulong bytesWritten = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.Enumerators.IEnumSourceLink2>(__this_native);
			__retVal = @this.GetNext(bufferSize, out bytesWritten, buffer);
			// Marshal - Convert managed data to native data.
			__bytesWritten_native = bytesWritten;
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	internal static void** CreateManagedVirtualFunctionTable()
	{
		void** vtable = (void**)System.Runtime.CompilerServices.RuntimeHelpers.AllocateTypeAssociatedMemory(typeof(DiaSharp.SDK.Enumerators.IEnumSourceLink2), sizeof(void*) * 11);
		{
			System.Runtime.InteropServices.NativeMemory.Copy(System.Runtime.InteropServices.Marshalling.StrategyBasedComWrappers.DefaultIUnknownInterfaceDetailsStrategy.GetIUnknownDerivedDetails(typeof(DiaSharp.SDK.Enumerators.IEnumSourceLink).TypeHandle).ManagedVirtualMethodTable, vtable, (nuint)(sizeof(void*) * 9));
		}

		{
			vtable[9] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, ulong*, int> )&ABI_SizeOfNext;
			vtable[10] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, ulong, ulong*, byte*, int> )&ABI_GetNext;
		}

		return vtable;
	}
}

namespace DiaSharp.SDK.Enumerators
{
	[System.Runtime.InteropServices.Marshalling.IUnknownDerivedAttribute<InterfaceInformation, InterfaceImplementation>]
	public partial interface IEnumSourceLink2
	{
		[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
		[System.Runtime.InteropServices.PreserveSigAttribute()]
		new int Count(out uint count) => ((DiaSharp.SDK.Enumerators.IEnumSourceLink)this).Count(out count);

		[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
		[System.Runtime.InteropServices.PreserveSigAttribute()]
		new int SizeOfNext(out uint size) => ((DiaSharp.SDK.Enumerators.IEnumSourceLink)this).SizeOfNext(out size);

		[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
		[System.Runtime.InteropServices.PreserveSigAttribute()]
		new unsafe int GetNext(uint bufferSize, out uint bytesWritten, byte* buffer) => ((DiaSharp.SDK.Enumerators.IEnumSourceLink)this).GetNext(bufferSize, out bytesWritten, buffer);

		[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
		[System.Runtime.InteropServices.PreserveSigAttribute()]
		new int Skip(uint byteCount) => ((DiaSharp.SDK.Enumerators.IEnumSourceLink)this).Skip(byteCount);

		[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
		[System.Runtime.InteropServices.PreserveSigAttribute()]
		new int Reset() => ((DiaSharp.SDK.Enumerators.IEnumSourceLink)this).Reset();

		[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
		[System.Runtime.InteropServices.PreserveSigAttribute()]
		new int Clone(out DiaSharp.SDK.Enumerators.IEnumSourceLink enumerator) => ((DiaSharp.SDK.Enumerators.IEnumSourceLink)this).Clone(out enumerator);
	}
}