// <auto-generated />
#pragma warning disable CS0612, CS0618
file unsafe class InterfaceInformation : System.Runtime.InteropServices.Marshalling.IIUnknownInterfaceType
{
	public static System.Guid Iid { get; } = new(new System.ReadOnlySpan<byte>(new byte[] { 224, 245, 1, 43, 219, 152, 36, 72, 169, 160, 81, 146, 131, 59, 239, 71 }));

	private static void** _vtable;
	public static void** ManagedVirtualMethodTable => _vtable != null ? _vtable : (_vtable = InterfaceImplementation.CreateManagedVirtualFunctionTable());
}

[System.Runtime.InteropServices.DynamicInterfaceCastableImplementationAttribute]
file unsafe partial interface InterfaceImplementation : DiaSharp.SDK.Enumerators.IEnumNamedStreams
{
	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.Enumerators.IEnumNamedStreams.GetNewEnum(out DiaSharp.Interop.IEnumVARIANT enumerator)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.Enumerators.IEnumNamedStreams));
		bool __invokeSucceeded = default;
		System.Runtime.CompilerServices.Unsafe.SkipInit(out enumerator);
		void* __enumerator_native = default;
		int __retVal = default;
		try
		{
			{
				__retVal = ((delegate* unmanaged[MemberFunction]<void*, void**, int> )__vtable_native[3])(__this, &__enumerator_native);
			}

			__invokeSucceeded = true;
			System.GC.KeepAlive(this);
			// Unmarshal - Convert native data to managed data.
			enumerator = System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.Interop.IEnumVARIANT>.ConvertToManaged(__enumerator_native);
		}
		finally
		{
			if (__invokeSucceeded)
			{
				// CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
				System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.Interop.IEnumVARIANT>.Free(__enumerator_native);
			}
		}

		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.Enumerators.IEnumNamedStreams.GetCount(out int count)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.Enumerators.IEnumNamedStreams));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out count);
		int __retVal;
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (int* __count_native = &count)
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, int*, int> )__vtable_native[4])(__this, __count_native);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.Enumerators.IEnumNamedStreams.GetNext(out string name)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.Enumerators.IEnumNamedStreams));
		bool __invokeSucceeded = default;
		System.Runtime.CompilerServices.Unsafe.SkipInit(out name);
		ushort* __name_native = default;
		int __retVal = default;
		try
		{
			{
				__retVal = ((delegate* unmanaged[MemberFunction]<void*, ushort**, int> )__vtable_native[5])(__this, &__name_native);
			}

			__invokeSucceeded = true;
			System.GC.KeepAlive(this);
			// Unmarshal - Convert native data to managed data.
			name = System.Runtime.InteropServices.Marshalling.BStrStringMarshaller.ConvertToManaged(__name_native);
		}
		finally
		{
			if (__invokeSucceeded)
			{
				// CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
				System.Runtime.InteropServices.Marshalling.BStrStringMarshaller.Free(__name_native);
			}
		}

		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.Enumerators.IEnumNamedStreams.Skip(uint nameCount)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.Enumerators.IEnumNamedStreams));
		int __retVal;
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, uint, int> )__vtable_native[6])(__this, nameCount);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.Enumerators.IEnumNamedStreams.Reset()
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.Enumerators.IEnumNamedStreams));
		int __retVal;
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, int> )__vtable_native[7])(__this);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.Enumerators.IEnumNamedStreams.Clone(out DiaSharp.SDK.Enumerators.IEnumNamedStreams enumerator)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.Enumerators.IEnumNamedStreams));
		bool __invokeSucceeded = default;
		System.Runtime.CompilerServices.Unsafe.SkipInit(out enumerator);
		void* __enumerator_native = default;
		int __retVal = default;
		try
		{
			{
				__retVal = ((delegate* unmanaged[MemberFunction]<void*, void**, int> )__vtable_native[8])(__this, &__enumerator_native);
			}

			__invokeSucceeded = true;
			System.GC.KeepAlive(this);
			// Unmarshal - Convert native data to managed data.
			enumerator = System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Enumerators.IEnumNamedStreams>.ConvertToManaged(__enumerator_native);
		}
		finally
		{
			if (__invokeSucceeded)
			{
				// CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
				System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Enumerators.IEnumNamedStreams>.Free(__enumerator_native);
			}
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetNewEnum(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, void** __enumerator_native__param)
	{
		DiaSharp.SDK.Enumerators.IEnumNamedStreams @this = default;
		ref void* __enumerator_native = ref *__enumerator_native__param;
		DiaSharp.Interop.IEnumVARIANT enumerator = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.Enumerators.IEnumNamedStreams>(__this_native);
			__retVal = @this.GetNewEnum(out enumerator);
			// Marshal - Convert managed data to native data.
			__enumerator_native = (void*)System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.Interop.IEnumVARIANT>.ConvertToUnmanaged(enumerator);
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetCount(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, int* __count_native__param)
	{
		DiaSharp.SDK.Enumerators.IEnumNamedStreams @this = default;
		ref int __count_native = ref *__count_native__param;
		int count = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.Enumerators.IEnumNamedStreams>(__this_native);
			__retVal = @this.GetCount(out count);
			// Marshal - Convert managed data to native data.
			__count_native = count;
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetNext(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, ushort** __name_native__param)
	{
		DiaSharp.SDK.Enumerators.IEnumNamedStreams @this = default;
		ref ushort* __name_native = ref *__name_native__param;
		string name = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.Enumerators.IEnumNamedStreams>(__this_native);
			__retVal = @this.GetNext(out name);
			// Marshal - Convert managed data to native data.
			__name_native = (ushort*)System.Runtime.InteropServices.Marshalling.BStrStringMarshaller.ConvertToUnmanaged(name);
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_Skip(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, uint nameCount)
	{
		DiaSharp.SDK.Enumerators.IEnumNamedStreams @this = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.Enumerators.IEnumNamedStreams>(__this_native);
			__retVal = @this.Skip(nameCount);
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_Reset(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native)
	{
		DiaSharp.SDK.Enumerators.IEnumNamedStreams @this = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.Enumerators.IEnumNamedStreams>(__this_native);
			__retVal = @this.Reset();
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_Clone(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, void** __enumerator_native__param)
	{
		DiaSharp.SDK.Enumerators.IEnumNamedStreams @this = default;
		ref void* __enumerator_native = ref *__enumerator_native__param;
		DiaSharp.SDK.Enumerators.IEnumNamedStreams enumerator = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.Enumerators.IEnumNamedStreams>(__this_native);
			__retVal = @this.Clone(out enumerator);
			// Marshal - Convert managed data to native data.
			__enumerator_native = (void*)System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Enumerators.IEnumNamedStreams>.ConvertToUnmanaged(enumerator);
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	internal static void** CreateManagedVirtualFunctionTable()
	{
		void** vtable = (void**)System.Runtime.CompilerServices.RuntimeHelpers.AllocateTypeAssociatedMemory(typeof(DiaSharp.SDK.Enumerators.IEnumNamedStreams), sizeof(void*) * 9);
		{
			nint v0, v1, v2;
			System.Runtime.InteropServices.ComWrappers.GetIUnknownImpl(out v0, out v1, out v2);
			vtable[0] = (void*)v0;
			vtable[1] = (void*)v1;
			vtable[2] = (void*)v2;
		}

		{
			vtable[3] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, void**, int> )&ABI_GetNewEnum;
			vtable[4] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, int*, int> )&ABI_GetCount;
			vtable[5] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, ushort**, int> )&ABI_GetNext;
			vtable[6] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, uint, int> )&ABI_Skip;
			vtable[7] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, int> )&ABI_Reset;
			vtable[8] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, void**, int> )&ABI_Clone;
		}

		return vtable;
	}
}

namespace DiaSharp.SDK.Enumerators
{
	[System.Runtime.InteropServices.Marshalling.IUnknownDerivedAttribute<InterfaceInformation, InterfaceImplementation>]
	public partial interface IEnumNamedStreams
	{
	}
}