// <auto-generated />
#pragma warning disable CS0612, CS0618
file unsafe class InterfaceInformation : System.Runtime.InteropServices.Marshalling.IIUnknownInterfaceType
{
	public static System.Guid Iid { get; } = new(new System.ReadOnlySpan<byte>(new byte[] { 2, 189, 69, 30, 69, 190, 113, 77, 186, 50, 14, 87, 108, 252, 213, 159 }));

	private static void** _vtable;
	public static void** ManagedVirtualMethodTable => _vtable != null ? _vtable : (_vtable = InterfaceImplementation.CreateManagedVirtualFunctionTable());
}

[System.Runtime.InteropServices.DynamicInterfaceCastableImplementationAttribute]
file unsafe partial interface InterfaceImplementation : DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx
{
	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx.GetSymbolByAddress(bool promoteBlockSymbols, uint sectionNumber, uint offset, out DiaSharp.SDK.Symbols.ISymbol symbol)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx));
		bool __invokeSucceeded = default;
		System.Runtime.CompilerServices.Unsafe.SkipInit(out symbol);
		int __promoteBlockSymbols_native = default;
		void* __symbol_native = default;
		int __retVal = default;
		try
		{
			// Marshal - Convert managed data to native data.
			__promoteBlockSymbols_native = (int)(promoteBlockSymbols ? 1 : 0);
			{
				__retVal = ((delegate* unmanaged[MemberFunction]<void*, int, uint, uint, void**, int> )__vtable_native[9])(__this, __promoteBlockSymbols_native, sectionNumber, offset, &__symbol_native);
			}

			__invokeSucceeded = true;
			System.GC.KeepAlive(this);
			// Unmarshal - Convert native data to managed data.
			symbol = System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Symbols.ISymbol>.ConvertToManaged(__symbol_native);
		}
		finally
		{
			if (__invokeSucceeded)
			{
				// CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
				System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Symbols.ISymbol>.Free(__symbol_native);
			}
		}

		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx.GetSymbolByRVA(bool promoteBlockSymbols, uint relativeVirtualAddress, out DiaSharp.SDK.Symbols.ISymbol symbol)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx));
		bool __invokeSucceeded = default;
		System.Runtime.CompilerServices.Unsafe.SkipInit(out symbol);
		int __promoteBlockSymbols_native = default;
		void* __symbol_native = default;
		int __retVal = default;
		try
		{
			// Marshal - Convert managed data to native data.
			__promoteBlockSymbols_native = (int)(promoteBlockSymbols ? 1 : 0);
			{
				__retVal = ((delegate* unmanaged[MemberFunction]<void*, int, uint, void**, int> )__vtable_native[10])(__this, __promoteBlockSymbols_native, relativeVirtualAddress, &__symbol_native);
			}

			__invokeSucceeded = true;
			System.GC.KeepAlive(this);
			// Unmarshal - Convert native data to managed data.
			symbol = System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Symbols.ISymbol>.ConvertToManaged(__symbol_native);
		}
		finally
		{
			if (__invokeSucceeded)
			{
				// CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
				System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Symbols.ISymbol>.Free(__symbol_native);
			}
		}

		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx.GetSymbolByVA(bool promoteBlockSymbols, ulong virtualAddress, out DiaSharp.SDK.Symbols.ISymbol symbol)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx));
		bool __invokeSucceeded = default;
		System.Runtime.CompilerServices.Unsafe.SkipInit(out symbol);
		int __promoteBlockSymbols_native = default;
		void* __symbol_native = default;
		int __retVal = default;
		try
		{
			// Marshal - Convert managed data to native data.
			__promoteBlockSymbols_native = (int)(promoteBlockSymbols ? 1 : 0);
			{
				__retVal = ((delegate* unmanaged[MemberFunction]<void*, int, ulong, void**, int> )__vtable_native[11])(__this, __promoteBlockSymbols_native, virtualAddress, &__symbol_native);
			}

			__invokeSucceeded = true;
			System.GC.KeepAlive(this);
			// Unmarshal - Convert native data to managed data.
			symbol = System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Symbols.ISymbol>.ConvertToManaged(__symbol_native);
		}
		finally
		{
			if (__invokeSucceeded)
			{
				// CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
				System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Symbols.ISymbol>.Free(__symbol_native);
			}
		}

		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	unsafe int DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx.GetNext(bool promoteBlockSymbols, uint symbolCount, void** symbols, out uint symbolsFetched)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out symbolsFetched);
		int __promoteBlockSymbols_native;
		int __retVal;
		// Marshal - Convert managed data to native data.
		__promoteBlockSymbols_native = (int)(promoteBlockSymbols ? 1 : 0);
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (uint* __symbolsFetched_native = &symbolsFetched)
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, int, uint, void**, uint*, int> )__vtable_native[12])(__this, __promoteBlockSymbols_native, symbolCount, symbols, __symbolsFetched_native);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	unsafe int DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx.Prev(bool promoteBlockSymbols, uint symbolCount, void** symbols, out uint symbolsFetched)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out symbolsFetched);
		int __promoteBlockSymbols_native;
		int __retVal;
		// Marshal - Convert managed data to native data.
		__promoteBlockSymbols_native = (int)(promoteBlockSymbols ? 1 : 0);
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (uint* __symbolsFetched_native = &symbolsFetched)
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, int, uint, void**, uint*, int> )__vtable_native[13])(__this, __promoteBlockSymbols_native, symbolCount, symbols, __symbolsFetched_native);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx.GetSymbolByAddress(uint sectionNumber, uint offset, out DiaSharp.SDK.Symbols.ISymbol symbol)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx));
		bool __invokeSucceeded = default;
		System.Runtime.CompilerServices.Unsafe.SkipInit(out symbol);
		void* __symbol_native = default;
		int __retVal = default;
		try
		{
			{
				__retVal = ((delegate* unmanaged[MemberFunction]<void*, uint, uint, void**, int> )__vtable_native[3])(__this, sectionNumber, offset, &__symbol_native);
			}

			__invokeSucceeded = true;
			System.GC.KeepAlive(this);
			// Unmarshal - Convert native data to managed data.
			symbol = System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Symbols.ISymbol>.ConvertToManaged(__symbol_native);
		}
		finally
		{
			if (__invokeSucceeded)
			{
				// CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
				System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Symbols.ISymbol>.Free(__symbol_native);
			}
		}

		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx.GetSymbolByRVA(uint relativeVirtualAddress, out DiaSharp.SDK.Symbols.ISymbol symbol)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx));
		bool __invokeSucceeded = default;
		System.Runtime.CompilerServices.Unsafe.SkipInit(out symbol);
		void* __symbol_native = default;
		int __retVal = default;
		try
		{
			{
				__retVal = ((delegate* unmanaged[MemberFunction]<void*, uint, void**, int> )__vtable_native[4])(__this, relativeVirtualAddress, &__symbol_native);
			}

			__invokeSucceeded = true;
			System.GC.KeepAlive(this);
			// Unmarshal - Convert native data to managed data.
			symbol = System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Symbols.ISymbol>.ConvertToManaged(__symbol_native);
		}
		finally
		{
			if (__invokeSucceeded)
			{
				// CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
				System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Symbols.ISymbol>.Free(__symbol_native);
			}
		}

		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx.GetSymbolByVA(ulong virtualAddress, out DiaSharp.SDK.Symbols.ISymbol symbol)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx));
		bool __invokeSucceeded = default;
		System.Runtime.CompilerServices.Unsafe.SkipInit(out symbol);
		void* __symbol_native = default;
		int __retVal = default;
		try
		{
			{
				__retVal = ((delegate* unmanaged[MemberFunction]<void*, ulong, void**, int> )__vtable_native[5])(__this, virtualAddress, &__symbol_native);
			}

			__invokeSucceeded = true;
			System.GC.KeepAlive(this);
			// Unmarshal - Convert native data to managed data.
			symbol = System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Symbols.ISymbol>.ConvertToManaged(__symbol_native);
		}
		finally
		{
			if (__invokeSucceeded)
			{
				// CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
				System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Symbols.ISymbol>.Free(__symbol_native);
			}
		}

		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	unsafe int DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx.GetNext(uint symbolCount, void** symbols, out uint symbolsFetched)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out symbolsFetched);
		int __retVal;
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (uint* __symbolsFetched_native = &symbolsFetched)
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, uint, void**, uint*, int> )__vtable_native[6])(__this, symbolCount, symbols, __symbolsFetched_native);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	unsafe int DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx.Prev(uint symbolCount, void** symbols, out uint symbolsFetched)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out symbolsFetched);
		int __retVal;
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (uint* __symbolsFetched_native = &symbolsFetched)
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, uint, void**, uint*, int> )__vtable_native[7])(__this, symbolCount, symbols, __symbolsFetched_native);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx.Clone(out DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress enumeator)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx));
		bool __invokeSucceeded = default;
		System.Runtime.CompilerServices.Unsafe.SkipInit(out enumeator);
		void* __enumeator_native = default;
		int __retVal = default;
		try
		{
			{
				__retVal = ((delegate* unmanaged[MemberFunction]<void*, void**, int> )__vtable_native[8])(__this, &__enumeator_native);
			}

			__invokeSucceeded = true;
			System.GC.KeepAlive(this);
			// Unmarshal - Convert native data to managed data.
			enumeator = System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress>.ConvertToManaged(__enumeator_native);
		}
		finally
		{
			if (__invokeSucceeded)
			{
				// CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
				System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress>.Free(__enumeator_native);
			}
		}

		return __retVal;
	}

	int DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress.GetSymbolByAddress(uint sectionNumber, uint offset, out DiaSharp.SDK.Symbols.ISymbol symbol) => throw new System.Diagnostics.UnreachableException();
	int DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress.GetSymbolByRVA(uint relativeVirtualAddress, out DiaSharp.SDK.Symbols.ISymbol symbol) => throw new System.Diagnostics.UnreachableException();
	int DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress.GetSymbolByVA(ulong virtualAddress, out DiaSharp.SDK.Symbols.ISymbol symbol) => throw new System.Diagnostics.UnreachableException();
	int DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress.GetNext(uint symbolCount, void** symbols, out uint symbolsFetched) => throw new System.Diagnostics.UnreachableException();
	int DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress.Prev(uint symbolCount, void** symbols, out uint symbolsFetched) => throw new System.Diagnostics.UnreachableException();
	int DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress.Clone(out DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress enumeator) => throw new System.Diagnostics.UnreachableException();

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetSymbolByAddress(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, int __promoteBlockSymbols_native, uint sectionNumber, uint offset, void** __symbol_native__param)
	{
		DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx @this = default;
		bool promoteBlockSymbols = default;
		ref void* __symbol_native = ref *__symbol_native__param;
		DiaSharp.SDK.Symbols.ISymbol symbol = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			promoteBlockSymbols = __promoteBlockSymbols_native != 0;
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx>(__this_native);
			__retVal = @this.GetSymbolByAddress(promoteBlockSymbols, sectionNumber, offset, out symbol);
			// Marshal - Convert managed data to native data.
			__symbol_native = (void*)System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Symbols.ISymbol>.ConvertToUnmanaged(symbol);
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetSymbolByRVA(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, int __promoteBlockSymbols_native, uint relativeVirtualAddress, void** __symbol_native__param)
	{
		DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx @this = default;
		bool promoteBlockSymbols = default;
		ref void* __symbol_native = ref *__symbol_native__param;
		DiaSharp.SDK.Symbols.ISymbol symbol = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			promoteBlockSymbols = __promoteBlockSymbols_native != 0;
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx>(__this_native);
			__retVal = @this.GetSymbolByRVA(promoteBlockSymbols, relativeVirtualAddress, out symbol);
			// Marshal - Convert managed data to native data.
			__symbol_native = (void*)System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Symbols.ISymbol>.ConvertToUnmanaged(symbol);
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetSymbolByVA(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, int __promoteBlockSymbols_native, ulong virtualAddress, void** __symbol_native__param)
	{
		DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx @this = default;
		bool promoteBlockSymbols = default;
		ref void* __symbol_native = ref *__symbol_native__param;
		DiaSharp.SDK.Symbols.ISymbol symbol = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			promoteBlockSymbols = __promoteBlockSymbols_native != 0;
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx>(__this_native);
			__retVal = @this.GetSymbolByVA(promoteBlockSymbols, virtualAddress, out symbol);
			// Marshal - Convert managed data to native data.
			__symbol_native = (void*)System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Symbols.ISymbol>.ConvertToUnmanaged(symbol);
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetNext(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, int __promoteBlockSymbols_native, uint symbolCount, void** symbols, uint* __symbolsFetched_native__param)
	{
		DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx @this = default;
		bool promoteBlockSymbols = default;
		ref uint __symbolsFetched_native = ref *__symbolsFetched_native__param;
		uint symbolsFetched = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			promoteBlockSymbols = __promoteBlockSymbols_native != 0;
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx>(__this_native);
			__retVal = @this.GetNext(promoteBlockSymbols, symbolCount, symbols, out symbolsFetched);
			// Marshal - Convert managed data to native data.
			__symbolsFetched_native = symbolsFetched;
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_Prev(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, int __promoteBlockSymbols_native, uint symbolCount, void** symbols, uint* __symbolsFetched_native__param)
	{
		DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx @this = default;
		bool promoteBlockSymbols = default;
		ref uint __symbolsFetched_native = ref *__symbolsFetched_native__param;
		uint symbolsFetched = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			promoteBlockSymbols = __promoteBlockSymbols_native != 0;
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx>(__this_native);
			__retVal = @this.Prev(promoteBlockSymbols, symbolCount, symbols, out symbolsFetched);
			// Marshal - Convert managed data to native data.
			__symbolsFetched_native = symbolsFetched;
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	internal static void** CreateManagedVirtualFunctionTable()
	{
		void** vtable = (void**)System.Runtime.CompilerServices.RuntimeHelpers.AllocateTypeAssociatedMemory(typeof(DiaSharp.SDK.Enumerators.IEnumSymbolsByAddressEx), sizeof(void*) * 14);
		{
			System.Runtime.InteropServices.NativeMemory.Copy(System.Runtime.InteropServices.Marshalling.StrategyBasedComWrappers.DefaultIUnknownInterfaceDetailsStrategy.GetIUnknownDerivedDetails(typeof(DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress).TypeHandle).ManagedVirtualMethodTable, vtable, (nuint)(sizeof(void*) * 9));
		}

		{
			vtable[9] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, int, uint, uint, void**, int> )&ABI_GetSymbolByAddress;
			vtable[10] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, int, uint, void**, int> )&ABI_GetSymbolByRVA;
			vtable[11] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, int, ulong, void**, int> )&ABI_GetSymbolByVA;
			vtable[12] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, int, uint, void**, uint*, int> )&ABI_GetNext;
			vtable[13] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, int, uint, void**, uint*, int> )&ABI_Prev;
		}

		return vtable;
	}
}

namespace DiaSharp.SDK.Enumerators
{
	[System.Runtime.InteropServices.Marshalling.IUnknownDerivedAttribute<InterfaceInformation, InterfaceImplementation>]
	public partial interface IEnumSymbolsByAddressEx
	{
		[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
		[System.Runtime.InteropServices.PreserveSigAttribute()]
		new int GetSymbolByAddress(uint sectionNumber, uint offset, out DiaSharp.SDK.Symbols.ISymbol symbol) => ((DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress)this).GetSymbolByAddress(sectionNumber, offset, out symbol);

		[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
		[System.Runtime.InteropServices.PreserveSigAttribute()]
		new int GetSymbolByRVA(uint relativeVirtualAddress, out DiaSharp.SDK.Symbols.ISymbol symbol) => ((DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress)this).GetSymbolByRVA(relativeVirtualAddress, out symbol);

		[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
		[System.Runtime.InteropServices.PreserveSigAttribute()]
		new int GetSymbolByVA(ulong virtualAddress, out DiaSharp.SDK.Symbols.ISymbol symbol) => ((DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress)this).GetSymbolByVA(virtualAddress, out symbol);

		[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
		[System.Runtime.InteropServices.PreserveSigAttribute()]
		new unsafe int GetNext(uint symbolCount, void** symbols, out uint symbolsFetched) => ((DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress)this).GetNext(symbolCount, symbols, out symbolsFetched);

		[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
		[System.Runtime.InteropServices.PreserveSigAttribute()]
		new unsafe int Prev(uint symbolCount, void** symbols, out uint symbolsFetched) => ((DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress)this).Prev(symbolCount, symbols, out symbolsFetched);

		[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
		[System.Runtime.InteropServices.PreserveSigAttribute()]
		new int Clone(out DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress enumeator) => ((DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress)this).Clone(out enumeator);
	}
}