// <auto-generated />
#pragma warning disable CS0612, CS0618
file unsafe class InterfaceInformation : System.Runtime.InteropServices.Marshalling.IIUnknownInterfaceType
{
	public static System.Guid Iid { get; } = new(new System.ReadOnlySpan<byte>(new byte[] { 156, 125, 75, 98, 234, 36, 33, 68, 157, 6, 59, 87, 116, 113, 193, 250 }));

	private static void** _vtable;
	public static void** ManagedVirtualMethodTable => _vtable != null ? _vtable : (_vtable = InterfaceImplementation.CreateManagedVirtualFunctionTable());
}

[System.Runtime.InteropServices.DynamicInterfaceCastableImplementationAttribute]
file unsafe partial interface InterfaceImplementation : DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress
{
	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress.GetSymbolByAddress(uint sectionNumber, uint offset, out DiaSharp.SDK.Symbols.ISymbol symbol)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress));
		bool __invokeSucceeded = default;
		System.Runtime.CompilerServices.Unsafe.SkipInit(out symbol);
		void* __symbol_native = default;
		int __retVal = default;
		try
		{
			{
				__retVal = ((delegate* unmanaged[MemberFunction]<void*, uint, uint, void**, int> )__vtable_native[3])(__this, sectionNumber, offset, &__symbol_native);
			}

			__invokeSucceeded = true;
			System.GC.KeepAlive(this);
			// Unmarshal - Convert native data to managed data.
			symbol = System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Symbols.ISymbol>.ConvertToManaged(__symbol_native);
		}
		finally
		{
			if (__invokeSucceeded)
			{
				// CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
				System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Symbols.ISymbol>.Free(__symbol_native);
			}
		}

		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress.GetSymbolByRVA(uint relativeVirtualAddress, out DiaSharp.SDK.Symbols.ISymbol symbol)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress));
		bool __invokeSucceeded = default;
		System.Runtime.CompilerServices.Unsafe.SkipInit(out symbol);
		void* __symbol_native = default;
		int __retVal = default;
		try
		{
			{
				__retVal = ((delegate* unmanaged[MemberFunction]<void*, uint, void**, int> )__vtable_native[4])(__this, relativeVirtualAddress, &__symbol_native);
			}

			__invokeSucceeded = true;
			System.GC.KeepAlive(this);
			// Unmarshal - Convert native data to managed data.
			symbol = System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Symbols.ISymbol>.ConvertToManaged(__symbol_native);
		}
		finally
		{
			if (__invokeSucceeded)
			{
				// CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
				System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Symbols.ISymbol>.Free(__symbol_native);
			}
		}

		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress.GetSymbolByVA(ulong virtualAddress, out DiaSharp.SDK.Symbols.ISymbol symbol)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress));
		bool __invokeSucceeded = default;
		System.Runtime.CompilerServices.Unsafe.SkipInit(out symbol);
		void* __symbol_native = default;
		int __retVal = default;
		try
		{
			{
				__retVal = ((delegate* unmanaged[MemberFunction]<void*, ulong, void**, int> )__vtable_native[5])(__this, virtualAddress, &__symbol_native);
			}

			__invokeSucceeded = true;
			System.GC.KeepAlive(this);
			// Unmarshal - Convert native data to managed data.
			symbol = System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Symbols.ISymbol>.ConvertToManaged(__symbol_native);
		}
		finally
		{
			if (__invokeSucceeded)
			{
				// CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
				System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Symbols.ISymbol>.Free(__symbol_native);
			}
		}

		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	unsafe int DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress.GetNext(uint symbolCount, void** symbols, out uint symbolsFetched)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out symbolsFetched);
		int __retVal;
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (uint* __symbolsFetched_native = &symbolsFetched)
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, uint, void**, uint*, int> )__vtable_native[6])(__this, symbolCount, symbols, __symbolsFetched_native);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	unsafe int DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress.Prev(uint symbolCount, void** symbols, out uint symbolsFetched)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out symbolsFetched);
		int __retVal;
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (uint* __symbolsFetched_native = &symbolsFetched)
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, uint, void**, uint*, int> )__vtable_native[7])(__this, symbolCount, symbols, __symbolsFetched_native);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress.Clone(out DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress enumeator)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress));
		bool __invokeSucceeded = default;
		System.Runtime.CompilerServices.Unsafe.SkipInit(out enumeator);
		void* __enumeator_native = default;
		int __retVal = default;
		try
		{
			{
				__retVal = ((delegate* unmanaged[MemberFunction]<void*, void**, int> )__vtable_native[8])(__this, &__enumeator_native);
			}

			__invokeSucceeded = true;
			System.GC.KeepAlive(this);
			// Unmarshal - Convert native data to managed data.
			enumeator = System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress>.ConvertToManaged(__enumeator_native);
		}
		finally
		{
			if (__invokeSucceeded)
			{
				// CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
				System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress>.Free(__enumeator_native);
			}
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetSymbolByAddress(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, uint sectionNumber, uint offset, void** __symbol_native__param)
	{
		DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress @this = default;
		ref void* __symbol_native = ref *__symbol_native__param;
		DiaSharp.SDK.Symbols.ISymbol symbol = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress>(__this_native);
			__retVal = @this.GetSymbolByAddress(sectionNumber, offset, out symbol);
			// Marshal - Convert managed data to native data.
			__symbol_native = (void*)System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Symbols.ISymbol>.ConvertToUnmanaged(symbol);
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetSymbolByRVA(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, uint relativeVirtualAddress, void** __symbol_native__param)
	{
		DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress @this = default;
		ref void* __symbol_native = ref *__symbol_native__param;
		DiaSharp.SDK.Symbols.ISymbol symbol = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress>(__this_native);
			__retVal = @this.GetSymbolByRVA(relativeVirtualAddress, out symbol);
			// Marshal - Convert managed data to native data.
			__symbol_native = (void*)System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Symbols.ISymbol>.ConvertToUnmanaged(symbol);
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetSymbolByVA(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, ulong virtualAddress, void** __symbol_native__param)
	{
		DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress @this = default;
		ref void* __symbol_native = ref *__symbol_native__param;
		DiaSharp.SDK.Symbols.ISymbol symbol = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress>(__this_native);
			__retVal = @this.GetSymbolByVA(virtualAddress, out symbol);
			// Marshal - Convert managed data to native data.
			__symbol_native = (void*)System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Symbols.ISymbol>.ConvertToUnmanaged(symbol);
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetNext(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, uint symbolCount, void** symbols, uint* __symbolsFetched_native__param)
	{
		DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress @this = default;
		ref uint __symbolsFetched_native = ref *__symbolsFetched_native__param;
		uint symbolsFetched = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress>(__this_native);
			__retVal = @this.GetNext(symbolCount, symbols, out symbolsFetched);
			// Marshal - Convert managed data to native data.
			__symbolsFetched_native = symbolsFetched;
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_Prev(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, uint symbolCount, void** symbols, uint* __symbolsFetched_native__param)
	{
		DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress @this = default;
		ref uint __symbolsFetched_native = ref *__symbolsFetched_native__param;
		uint symbolsFetched = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress>(__this_native);
			__retVal = @this.Prev(symbolCount, symbols, out symbolsFetched);
			// Marshal - Convert managed data to native data.
			__symbolsFetched_native = symbolsFetched;
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_Clone(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, void** __enumeator_native__param)
	{
		DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress @this = default;
		ref void* __enumeator_native = ref *__enumeator_native__param;
		DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress enumeator = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress>(__this_native);
			__retVal = @this.Clone(out enumeator);
			// Marshal - Convert managed data to native data.
			__enumeator_native = (void*)System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress>.ConvertToUnmanaged(enumeator);
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	internal static void** CreateManagedVirtualFunctionTable()
	{
		void** vtable = (void**)System.Runtime.CompilerServices.RuntimeHelpers.AllocateTypeAssociatedMemory(typeof(DiaSharp.SDK.Enumerators.IEnumSymbolsByAddress), sizeof(void*) * 9);
		{
			nint v0, v1, v2;
			System.Runtime.InteropServices.ComWrappers.GetIUnknownImpl(out v0, out v1, out v2);
			vtable[0] = (void*)v0;
			vtable[1] = (void*)v1;
			vtable[2] = (void*)v2;
		}

		{
			vtable[3] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, uint, uint, void**, int> )&ABI_GetSymbolByAddress;
			vtable[4] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, uint, void**, int> )&ABI_GetSymbolByRVA;
			vtable[5] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, ulong, void**, int> )&ABI_GetSymbolByVA;
			vtable[6] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, uint, void**, uint*, int> )&ABI_GetNext;
			vtable[7] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, uint, void**, uint*, int> )&ABI_Prev;
			vtable[8] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, void**, int> )&ABI_Clone;
		}

		return vtable;
	}
}

namespace DiaSharp.SDK.Enumerators
{
	[System.Runtime.InteropServices.Marshalling.IUnknownDerivedAttribute<InterfaceInformation, InterfaceImplementation>]
	public partial interface IEnumSymbolsByAddress
	{
	}
}