// <auto-generated />
#pragma warning disable CS0612, CS0618
file unsafe class InterfaceInformation : global::System.Runtime.InteropServices.Marshalling.IIUnknownInterfaceType
{
    public static global::System.Guid Iid { get; } = new(new global::System.ReadOnlySpan<byte>(new byte[] { 27, 27, 248, 33, 187, 197, 163, 66, 188, 79, 204, 186, 167, 91, 159, 25 }));

    private static void** _vtable;
    public static void** ManagedVirtualMethodTable => _vtable != null ? _vtable : (_vtable = InterfaceImplementation.CreateManagedVirtualFunctionTable());
}

[global::System.Runtime.InteropServices.DynamicInterfaceCastableImplementationAttribute]
file unsafe partial interface InterfaceImplementation : global::DiaSharp.StackWalk.IStackWalkHelper
{
    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.StackWalk.IStackWalkHelper.GetRegisterValue(global::DiaSharp.CodeView.HostRegister index, out ulong value)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.StackWalk.IStackWalkHelper));
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out value);
        int __retVal;
        // Pin - Pin data in preparation for calling the P/Invoke.
        fixed (ulong* __value_native = &value)
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, global::DiaSharp.CodeView.HostRegister, ulong*, int> )__vtable_native[3])(__this, index, __value_native);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.StackWalk.IStackWalkHelper.PutRegisterValue(global::DiaSharp.CodeView.HostRegister index, ulong value)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.StackWalk.IStackWalkHelper));
        int __retVal;
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, global::DiaSharp.CodeView.HostRegister, ulong, int> )__vtable_native[4])(__this, index, value);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    unsafe int global::DiaSharp.StackWalk.IStackWalkHelper.ReadMemory(global::DiaSharp.Native.MemoryType type, ulong virtualAddress, uint bufferSize, out uint bytesWritten, byte* buffer)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.StackWalk.IStackWalkHelper));
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out bytesWritten);
        int __retVal;
        // Pin - Pin data in preparation for calling the P/Invoke.
        fixed (uint* __bytesWritten_native = &bytesWritten)
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, global::DiaSharp.Native.MemoryType, ulong, uint, uint*, byte*, int> )__vtable_native[5])(__this, type, virtualAddress, bufferSize, __bytesWritten_native, buffer);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.StackWalk.IStackWalkHelper.SearchForReturnAddress(global::DiaSharp.SDK.IFrameData frame, out ulong address)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.StackWalk.IStackWalkHelper));
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out address);
        void* __frame_native = default;
        int __retVal = default;
        try
        {
            // Marshal - Convert managed data to native data.
            __frame_native = (void*)global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.SDK.IFrameData>.ConvertToUnmanaged(frame);
            // Pin - Pin data in preparation for calling the P/Invoke.
            fixed (ulong* __address_native = &address)
            {
                __retVal = ((delegate* unmanaged[MemberFunction]<void*, void*, ulong*, int> )__vtable_native[6])(__this, __frame_native, __address_native);
            }

            global::System.GC.KeepAlive(this);
        }
        finally
        {
            // CleanupCallerAllocated - Perform cleanup of caller allocated resources.
            global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.SDK.IFrameData>.Free(__frame_native);
        }

        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.StackWalk.IStackWalkHelper.SearchForReturnAddressStart(global::DiaSharp.SDK.IFrameData frame, ulong address, out ulong startAddress)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.StackWalk.IStackWalkHelper));
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out startAddress);
        void* __frame_native = default;
        int __retVal = default;
        try
        {
            // Marshal - Convert managed data to native data.
            __frame_native = (void*)global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.SDK.IFrameData>.ConvertToUnmanaged(frame);
            // Pin - Pin data in preparation for calling the P/Invoke.
            fixed (ulong* __startAddress_native = &startAddress)
            {
                __retVal = ((delegate* unmanaged[MemberFunction]<void*, void*, ulong, ulong*, int> )__vtable_native[7])(__this, __frame_native, address, __startAddress_native);
            }

            global::System.GC.KeepAlive(this);
        }
        finally
        {
            // CleanupCallerAllocated - Perform cleanup of caller allocated resources.
            global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.SDK.IFrameData>.Free(__frame_native);
        }

        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.StackWalk.IStackWalkHelper.GetFrameForVA(ulong va, out global::DiaSharp.SDK.IFrameData frame)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.StackWalk.IStackWalkHelper));
        bool __invokeSucceeded = default;
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out frame);
        void* __frame_native = default;
        int __retVal = default;
        try
        {
            {
                __retVal = ((delegate* unmanaged[MemberFunction]<void*, ulong, void**, int> )__vtable_native[8])(__this, va, &__frame_native);
            }

            __invokeSucceeded = true;
            global::System.GC.KeepAlive(this);
            // Unmarshal - Convert native data to managed data.
            frame = global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.SDK.IFrameData>.ConvertToManaged(__frame_native);
        }
        finally
        {
            if (__invokeSucceeded)
            {
                // CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
                global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.SDK.IFrameData>.Free(__frame_native);
            }
        }

        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.StackWalk.IStackWalkHelper.GetSymbolForVA(ulong va, out global::DiaSharp.SDK.Symbols.ISymbol symbol)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.StackWalk.IStackWalkHelper));
        bool __invokeSucceeded = default;
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out symbol);
        void* __symbol_native = default;
        int __retVal = default;
        try
        {
            {
                __retVal = ((delegate* unmanaged[MemberFunction]<void*, ulong, void**, int> )__vtable_native[9])(__this, va, &__symbol_native);
            }

            __invokeSucceeded = true;
            global::System.GC.KeepAlive(this);
            // Unmarshal - Convert native data to managed data.
            symbol = global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.SDK.Symbols.ISymbol>.ConvertToManaged(__symbol_native);
        }
        finally
        {
            if (__invokeSucceeded)
            {
                // CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
                global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.SDK.Symbols.ISymbol>.Free(__symbol_native);
            }
        }

        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    unsafe int global::DiaSharp.StackWalk.IStackWalkHelper.GetPDataForVA(ulong virtualAddress, uint bytesRequested, out uint bytesWritten, byte* buffer)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.StackWalk.IStackWalkHelper));
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out bytesWritten);
        int __retVal;
        // Pin - Pin data in preparation for calling the P/Invoke.
        fixed (uint* __bytesWritten_native = &bytesWritten)
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, ulong, uint, uint*, byte*, int> )__vtable_native[10])(__this, virtualAddress, bytesRequested, __bytesWritten_native, buffer);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.StackWalk.IStackWalkHelper.GetImageForVA(ulong virtualAddressContext, out ulong imageAddress)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.StackWalk.IStackWalkHelper));
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out imageAddress);
        int __retVal;
        // Pin - Pin data in preparation for calling the P/Invoke.
        fixed (ulong* __imageAddress_native = &imageAddress)
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, ulong, ulong*, int> )__vtable_native[11])(__this, virtualAddressContext, __imageAddress_native);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.StackWalk.IStackWalkHelper.GetAddressForVA(ulong virtualAddress, out uint equivalentSection, out uint fragmentCount)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.StackWalk.IStackWalkHelper));
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out equivalentSection);
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out fragmentCount);
        int __retVal;
        // Pin - Pin data in preparation for calling the P/Invoke.
        fixed (uint* __fragmentCount_native = &fragmentCount)
        fixed (uint* __equivalentSection_native = &equivalentSection)
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, ulong, uint*, uint*, int> )__vtable_native[12])(__this, virtualAddress, __equivalentSection_native, __fragmentCount_native);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.StackWalk.IStackWalkHelper.GetNumberOfFunctionFragmentsForVA(ulong functionAddress, uint functionSize, out uint fragmentCount)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.StackWalk.IStackWalkHelper));
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out fragmentCount);
        int __retVal;
        // Pin - Pin data in preparation for calling the P/Invoke.
        fixed (uint* __fragmentCount_native = &fragmentCount)
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, ulong, uint, uint*, int> )__vtable_native[13])(__this, functionAddress, functionSize, __fragmentCount_native);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    unsafe int global::DiaSharp.StackWalk.IStackWalkHelper.GetFunctionFragmentsForVA(ulong functionAddress, uint functionSize, uint fragmentCount, ulong* fragments, uint* fragmentLengths)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.StackWalk.IStackWalkHelper));
        int __retVal;
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, ulong, uint, uint, ulong*, uint*, int> )__vtable_native[14])(__this, functionAddress, functionSize, fragmentCount, fragments, fragmentLengths);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }
}

file unsafe partial interface InterfaceImplementation
{
    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_GetRegisterValue(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, global::DiaSharp.CodeView.HostRegister index, ulong* __value_native__param)
    {
        global::DiaSharp.StackWalk.IStackWalkHelper @this = default;
        ref ulong __value_native = ref *__value_native__param;
        ulong value = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.StackWalk.IStackWalkHelper>(__this_native);
            __retVal = @this.GetRegisterValue(index, out value);
            // Marshal - Convert managed data to native data.
            __value_native = value;
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_PutRegisterValue(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, global::DiaSharp.CodeView.HostRegister index, ulong value)
    {
        global::DiaSharp.StackWalk.IStackWalkHelper @this = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.StackWalk.IStackWalkHelper>(__this_native);
            __retVal = @this.PutRegisterValue(index, value);
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_ReadMemory(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, global::DiaSharp.Native.MemoryType type, ulong virtualAddress, uint bufferSize, uint* __bytesWritten_native__param, byte* buffer)
    {
        global::DiaSharp.StackWalk.IStackWalkHelper @this = default;
        ref uint __bytesWritten_native = ref *__bytesWritten_native__param;
        uint bytesWritten = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.StackWalk.IStackWalkHelper>(__this_native);
            __retVal = @this.ReadMemory(type, virtualAddress, bufferSize, out bytesWritten, buffer);
            // Marshal - Convert managed data to native data.
            __bytesWritten_native = bytesWritten;
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_SearchForReturnAddress(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, void* __frame_native, ulong* __address_native__param)
    {
        global::DiaSharp.StackWalk.IStackWalkHelper @this = default;
        global::DiaSharp.SDK.IFrameData frame = default;
        ref ulong __address_native = ref *__address_native__param;
        ulong address = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            frame = global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.SDK.IFrameData>.ConvertToManaged(__frame_native);
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.StackWalk.IStackWalkHelper>(__this_native);
            __retVal = @this.SearchForReturnAddress(frame, out address);
            // Marshal - Convert managed data to native data.
            __address_native = address;
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_SearchForReturnAddressStart(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, void* __frame_native, ulong address, ulong* __startAddress_native__param)
    {
        global::DiaSharp.StackWalk.IStackWalkHelper @this = default;
        global::DiaSharp.SDK.IFrameData frame = default;
        ref ulong __startAddress_native = ref *__startAddress_native__param;
        ulong startAddress = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            frame = global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.SDK.IFrameData>.ConvertToManaged(__frame_native);
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.StackWalk.IStackWalkHelper>(__this_native);
            __retVal = @this.SearchForReturnAddressStart(frame, address, out startAddress);
            // Marshal - Convert managed data to native data.
            __startAddress_native = startAddress;
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_GetFrameForVA(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, ulong va, void** __frame_native__param)
    {
        global::DiaSharp.StackWalk.IStackWalkHelper @this = default;
        ref void* __frame_native = ref *__frame_native__param;
        global::DiaSharp.SDK.IFrameData frame = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.StackWalk.IStackWalkHelper>(__this_native);
            __retVal = @this.GetFrameForVA(va, out frame);
            // Marshal - Convert managed data to native data.
            __frame_native = (void*)global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.SDK.IFrameData>.ConvertToUnmanaged(frame);
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_GetSymbolForVA(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, ulong va, void** __symbol_native__param)
    {
        global::DiaSharp.StackWalk.IStackWalkHelper @this = default;
        ref void* __symbol_native = ref *__symbol_native__param;
        global::DiaSharp.SDK.Symbols.ISymbol symbol = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.StackWalk.IStackWalkHelper>(__this_native);
            __retVal = @this.GetSymbolForVA(va, out symbol);
            // Marshal - Convert managed data to native data.
            __symbol_native = (void*)global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.SDK.Symbols.ISymbol>.ConvertToUnmanaged(symbol);
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_GetPDataForVA(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, ulong virtualAddress, uint bytesRequested, uint* __bytesWritten_native__param, byte* buffer)
    {
        global::DiaSharp.StackWalk.IStackWalkHelper @this = default;
        ref uint __bytesWritten_native = ref *__bytesWritten_native__param;
        uint bytesWritten = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.StackWalk.IStackWalkHelper>(__this_native);
            __retVal = @this.GetPDataForVA(virtualAddress, bytesRequested, out bytesWritten, buffer);
            // Marshal - Convert managed data to native data.
            __bytesWritten_native = bytesWritten;
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_GetImageForVA(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, ulong virtualAddressContext, ulong* __imageAddress_native__param)
    {
        global::DiaSharp.StackWalk.IStackWalkHelper @this = default;
        ref ulong __imageAddress_native = ref *__imageAddress_native__param;
        ulong imageAddress = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.StackWalk.IStackWalkHelper>(__this_native);
            __retVal = @this.GetImageForVA(virtualAddressContext, out imageAddress);
            // Marshal - Convert managed data to native data.
            __imageAddress_native = imageAddress;
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_GetAddressForVA(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, ulong virtualAddress, uint* __equivalentSection_native__param, uint* __fragmentCount_native__param)
    {
        global::DiaSharp.StackWalk.IStackWalkHelper @this = default;
        ref uint __equivalentSection_native = ref *__equivalentSection_native__param;
        uint equivalentSection = default;
        ref uint __fragmentCount_native = ref *__fragmentCount_native__param;
        uint fragmentCount = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.StackWalk.IStackWalkHelper>(__this_native);
            __retVal = @this.GetAddressForVA(virtualAddress, out equivalentSection, out fragmentCount);
            // Marshal - Convert managed data to native data.
            __fragmentCount_native = fragmentCount;
            __equivalentSection_native = equivalentSection;
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_GetNumberOfFunctionFragmentsForVA(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, ulong functionAddress, uint functionSize, uint* __fragmentCount_native__param)
    {
        global::DiaSharp.StackWalk.IStackWalkHelper @this = default;
        ref uint __fragmentCount_native = ref *__fragmentCount_native__param;
        uint fragmentCount = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.StackWalk.IStackWalkHelper>(__this_native);
            __retVal = @this.GetNumberOfFunctionFragmentsForVA(functionAddress, functionSize, out fragmentCount);
            // Marshal - Convert managed data to native data.
            __fragmentCount_native = fragmentCount;
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_GetFunctionFragmentsForVA(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, ulong functionAddress, uint functionSize, uint fragmentCount, ulong* fragments, uint* fragmentLengths)
    {
        global::DiaSharp.StackWalk.IStackWalkHelper @this = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.StackWalk.IStackWalkHelper>(__this_native);
            __retVal = @this.GetFunctionFragmentsForVA(functionAddress, functionSize, fragmentCount, fragments, fragmentLengths);
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }
}

file unsafe partial interface InterfaceImplementation
{
    internal static void** CreateManagedVirtualFunctionTable()
    {
        void** vtable = (void**)global::System.Runtime.CompilerServices.RuntimeHelpers.AllocateTypeAssociatedMemory(typeof(global::DiaSharp.StackWalk.IStackWalkHelper), sizeof(void*) * 15);
        {
            nint v0, v1, v2;
            global::System.Runtime.InteropServices.ComWrappers.GetIUnknownImpl(out v0, out v1, out v2);
            vtable[0] = (void*)v0;
            vtable[1] = (void*)v1;
            vtable[2] = (void*)v2;
        }

        {
            vtable[3] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, global::DiaSharp.CodeView.HostRegister, ulong*, int> )&ABI_GetRegisterValue;
            vtable[4] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, global::DiaSharp.CodeView.HostRegister, ulong, int> )&ABI_PutRegisterValue;
            vtable[5] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, global::DiaSharp.Native.MemoryType, ulong, uint, uint*, byte*, int> )&ABI_ReadMemory;
            vtable[6] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, void*, ulong*, int> )&ABI_SearchForReturnAddress;
            vtable[7] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, void*, ulong, ulong*, int> )&ABI_SearchForReturnAddressStart;
            vtable[8] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, ulong, void**, int> )&ABI_GetFrameForVA;
            vtable[9] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, ulong, void**, int> )&ABI_GetSymbolForVA;
            vtable[10] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, ulong, uint, uint*, byte*, int> )&ABI_GetPDataForVA;
            vtable[11] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, ulong, ulong*, int> )&ABI_GetImageForVA;
            vtable[12] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, ulong, uint*, uint*, int> )&ABI_GetAddressForVA;
            vtable[13] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, ulong, uint, uint*, int> )&ABI_GetNumberOfFunctionFragmentsForVA;
            vtable[14] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, ulong, uint, uint, ulong*, uint*, int> )&ABI_GetFunctionFragmentsForVA;
        }

        return vtable;
    }
}

namespace DiaSharp.StackWalk
{
    [global::System.Runtime.InteropServices.Marshalling.IUnknownDerivedAttribute<InterfaceInformation, InterfaceImplementation>]
    public partial interface IStackWalkHelper
    {
    }
}

namespace DiaSharp.StackWalk
{
    public partial interface IStackWalkHelper
    {
    }
}