// <auto-generated />
#pragma warning disable CS0612, CS0618
file unsafe class InterfaceInformation : global::System.Runtime.InteropServices.Marshalling.IIUnknownInterfaceType
{
    public static global::System.Guid Iid { get; } = new(new global::System.ReadOnlySpan<byte>(new byte[] { 144, 196, 34, 130, 123, 80, 239, 75, 179, 189, 65, 220, 167, 181, 147, 76 }));

    private static void** _vtable;
    public static void** ManagedVirtualMethodTable => _vtable != null ? _vtable : (_vtable = InterfaceImplementation.CreateManagedVirtualFunctionTable());
}

[global::System.Runtime.InteropServices.DynamicInterfaceCastableImplementationAttribute]
file unsafe partial interface InterfaceImplementation : global::DiaSharp.StackWalk.IStackWalkHelper2
{
    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.StackWalk.IStackWalkHelper2.GetPointerAuthenticationMask(ulong pointerValue, out ulong mask)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.StackWalk.IStackWalkHelper2));
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out mask);
        int __retVal;
        // Pin - Pin data in preparation for calling the P/Invoke.
        fixed (ulong* __mask_native = &mask)
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, ulong, ulong*, int> )__vtable_native[15])(__this, pointerValue, __mask_native);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.StackWalk.IStackWalkHelper2.GetRegisterValue(global::DiaSharp.CodeView.HostRegister index, out ulong value)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.StackWalk.IStackWalkHelper2));
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out value);
        int __retVal;
        // Pin - Pin data in preparation for calling the P/Invoke.
        fixed (ulong* __value_native = &value)
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, global::DiaSharp.CodeView.HostRegister, ulong*, int> )__vtable_native[3])(__this, index, __value_native);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.StackWalk.IStackWalkHelper2.PutRegisterValue(global::DiaSharp.CodeView.HostRegister index, ulong value)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.StackWalk.IStackWalkHelper2));
        int __retVal;
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, global::DiaSharp.CodeView.HostRegister, ulong, int> )__vtable_native[4])(__this, index, value);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    unsafe int global::DiaSharp.StackWalk.IStackWalkHelper2.ReadMemory(global::DiaSharp.Native.MemoryType type, ulong virtualAddress, uint bufferSize, out uint bytesWritten, byte* buffer)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.StackWalk.IStackWalkHelper2));
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out bytesWritten);
        int __retVal;
        // Pin - Pin data in preparation for calling the P/Invoke.
        fixed (uint* __bytesWritten_native = &bytesWritten)
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, global::DiaSharp.Native.MemoryType, ulong, uint, uint*, byte*, int> )__vtable_native[5])(__this, type, virtualAddress, bufferSize, __bytesWritten_native, buffer);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.StackWalk.IStackWalkHelper2.SearchForReturnAddress(global::DiaSharp.SDK.IFrameData frame, out ulong address)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.StackWalk.IStackWalkHelper2));
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out address);
        void* __frame_native = default;
        int __retVal = default;
        try
        {
            // Marshal - Convert managed data to native data.
            __frame_native = (void*)global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.SDK.IFrameData>.ConvertToUnmanaged(frame);
            // Pin - Pin data in preparation for calling the P/Invoke.
            fixed (ulong* __address_native = &address)
            {
                __retVal = ((delegate* unmanaged[MemberFunction]<void*, void*, ulong*, int> )__vtable_native[6])(__this, __frame_native, __address_native);
            }

            global::System.GC.KeepAlive(this);
        }
        finally
        {
            // CleanupCallerAllocated - Perform cleanup of caller allocated resources.
            global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.SDK.IFrameData>.Free(__frame_native);
        }

        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.StackWalk.IStackWalkHelper2.SearchForReturnAddressStart(global::DiaSharp.SDK.IFrameData frame, ulong address, out ulong startAddress)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.StackWalk.IStackWalkHelper2));
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out startAddress);
        void* __frame_native = default;
        int __retVal = default;
        try
        {
            // Marshal - Convert managed data to native data.
            __frame_native = (void*)global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.SDK.IFrameData>.ConvertToUnmanaged(frame);
            // Pin - Pin data in preparation for calling the P/Invoke.
            fixed (ulong* __startAddress_native = &startAddress)
            {
                __retVal = ((delegate* unmanaged[MemberFunction]<void*, void*, ulong, ulong*, int> )__vtable_native[7])(__this, __frame_native, address, __startAddress_native);
            }

            global::System.GC.KeepAlive(this);
        }
        finally
        {
            // CleanupCallerAllocated - Perform cleanup of caller allocated resources.
            global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.SDK.IFrameData>.Free(__frame_native);
        }

        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.StackWalk.IStackWalkHelper2.GetFrameForVA(ulong va, out global::DiaSharp.SDK.IFrameData frame)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.StackWalk.IStackWalkHelper2));
        bool __invokeSucceeded = default;
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out frame);
        void* __frame_native = default;
        int __retVal = default;
        try
        {
            {
                __retVal = ((delegate* unmanaged[MemberFunction]<void*, ulong, void**, int> )__vtable_native[8])(__this, va, &__frame_native);
            }

            __invokeSucceeded = true;
            global::System.GC.KeepAlive(this);
            // Unmarshal - Convert native data to managed data.
            frame = global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.SDK.IFrameData>.ConvertToManaged(__frame_native);
        }
        finally
        {
            if (__invokeSucceeded)
            {
                // CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
                global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.SDK.IFrameData>.Free(__frame_native);
            }
        }

        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.StackWalk.IStackWalkHelper2.GetSymbolForVA(ulong va, out global::DiaSharp.SDK.Symbols.ISymbol symbol)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.StackWalk.IStackWalkHelper2));
        bool __invokeSucceeded = default;
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out symbol);
        void* __symbol_native = default;
        int __retVal = default;
        try
        {
            {
                __retVal = ((delegate* unmanaged[MemberFunction]<void*, ulong, void**, int> )__vtable_native[9])(__this, va, &__symbol_native);
            }

            __invokeSucceeded = true;
            global::System.GC.KeepAlive(this);
            // Unmarshal - Convert native data to managed data.
            symbol = global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.SDK.Symbols.ISymbol>.ConvertToManaged(__symbol_native);
        }
        finally
        {
            if (__invokeSucceeded)
            {
                // CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
                global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.SDK.Symbols.ISymbol>.Free(__symbol_native);
            }
        }

        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    unsafe int global::DiaSharp.StackWalk.IStackWalkHelper2.GetPDataForVA(ulong virtualAddress, uint bytesRequested, out uint bytesWritten, byte* buffer)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.StackWalk.IStackWalkHelper2));
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out bytesWritten);
        int __retVal;
        // Pin - Pin data in preparation for calling the P/Invoke.
        fixed (uint* __bytesWritten_native = &bytesWritten)
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, ulong, uint, uint*, byte*, int> )__vtable_native[10])(__this, virtualAddress, bytesRequested, __bytesWritten_native, buffer);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.StackWalk.IStackWalkHelper2.GetImageForVA(ulong virtualAddressContext, out ulong imageAddress)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.StackWalk.IStackWalkHelper2));
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out imageAddress);
        int __retVal;
        // Pin - Pin data in preparation for calling the P/Invoke.
        fixed (ulong* __imageAddress_native = &imageAddress)
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, ulong, ulong*, int> )__vtable_native[11])(__this, virtualAddressContext, __imageAddress_native);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.StackWalk.IStackWalkHelper2.GetAddressForVA(ulong virtualAddress, out uint equivalentSection, out uint fragmentCount)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.StackWalk.IStackWalkHelper2));
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out equivalentSection);
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out fragmentCount);
        int __retVal;
        // Pin - Pin data in preparation for calling the P/Invoke.
        fixed (uint* __fragmentCount_native = &fragmentCount)
        fixed (uint* __equivalentSection_native = &equivalentSection)
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, ulong, uint*, uint*, int> )__vtable_native[12])(__this, virtualAddress, __equivalentSection_native, __fragmentCount_native);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.StackWalk.IStackWalkHelper2.GetNumberOfFunctionFragmentsForVA(ulong functionAddress, uint functionSize, out uint fragmentCount)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.StackWalk.IStackWalkHelper2));
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out fragmentCount);
        int __retVal;
        // Pin - Pin data in preparation for calling the P/Invoke.
        fixed (uint* __fragmentCount_native = &fragmentCount)
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, ulong, uint, uint*, int> )__vtable_native[13])(__this, functionAddress, functionSize, __fragmentCount_native);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    unsafe int global::DiaSharp.StackWalk.IStackWalkHelper2.GetFunctionFragmentsForVA(ulong functionAddress, uint functionSize, uint fragmentCount, ulong* fragments, uint* fragmentLengths)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.StackWalk.IStackWalkHelper2));
        int __retVal;
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, ulong, uint, uint, ulong*, uint*, int> )__vtable_native[14])(__this, functionAddress, functionSize, fragmentCount, fragments, fragmentLengths);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    int global::DiaSharp.StackWalk.IStackWalkHelper.GetRegisterValue(global::DiaSharp.CodeView.HostRegister index, out ulong value) => throw new global::System.Diagnostics.UnreachableException();
    int global::DiaSharp.StackWalk.IStackWalkHelper.PutRegisterValue(global::DiaSharp.CodeView.HostRegister index, ulong value) => throw new global::System.Diagnostics.UnreachableException();
    int global::DiaSharp.StackWalk.IStackWalkHelper.ReadMemory(global::DiaSharp.Native.MemoryType type, ulong virtualAddress, uint bufferSize, out uint bytesWritten, byte* buffer) => throw new global::System.Diagnostics.UnreachableException();
    int global::DiaSharp.StackWalk.IStackWalkHelper.SearchForReturnAddress(global::DiaSharp.SDK.IFrameData frame, out ulong address) => throw new global::System.Diagnostics.UnreachableException();
    int global::DiaSharp.StackWalk.IStackWalkHelper.SearchForReturnAddressStart(global::DiaSharp.SDK.IFrameData frame, ulong address, out ulong startAddress) => throw new global::System.Diagnostics.UnreachableException();
    int global::DiaSharp.StackWalk.IStackWalkHelper.GetFrameForVA(ulong va, out global::DiaSharp.SDK.IFrameData frame) => throw new global::System.Diagnostics.UnreachableException();
    int global::DiaSharp.StackWalk.IStackWalkHelper.GetSymbolForVA(ulong va, out global::DiaSharp.SDK.Symbols.ISymbol symbol) => throw new global::System.Diagnostics.UnreachableException();
    int global::DiaSharp.StackWalk.IStackWalkHelper.GetPDataForVA(ulong virtualAddress, uint bytesRequested, out uint bytesWritten, byte* buffer) => throw new global::System.Diagnostics.UnreachableException();
    int global::DiaSharp.StackWalk.IStackWalkHelper.GetImageForVA(ulong virtualAddressContext, out ulong imageAddress) => throw new global::System.Diagnostics.UnreachableException();
    int global::DiaSharp.StackWalk.IStackWalkHelper.GetAddressForVA(ulong virtualAddress, out uint equivalentSection, out uint fragmentCount) => throw new global::System.Diagnostics.UnreachableException();
    int global::DiaSharp.StackWalk.IStackWalkHelper.GetNumberOfFunctionFragmentsForVA(ulong functionAddress, uint functionSize, out uint fragmentCount) => throw new global::System.Diagnostics.UnreachableException();
    int global::DiaSharp.StackWalk.IStackWalkHelper.GetFunctionFragmentsForVA(ulong functionAddress, uint functionSize, uint fragmentCount, ulong* fragments, uint* fragmentLengths) => throw new global::System.Diagnostics.UnreachableException();
}

file unsafe partial interface InterfaceImplementation
{
    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_GetPointerAuthenticationMask(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, ulong pointerValue, ulong* __mask_native__param)
    {
        global::DiaSharp.StackWalk.IStackWalkHelper2 @this = default;
        ref ulong __mask_native = ref *__mask_native__param;
        ulong mask = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.StackWalk.IStackWalkHelper2>(__this_native);
            __retVal = @this.GetPointerAuthenticationMask(pointerValue, out mask);
            // Marshal - Convert managed data to native data.
            __mask_native = mask;
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }
}

file unsafe partial interface InterfaceImplementation
{
    internal static void** CreateManagedVirtualFunctionTable()
    {
        void** vtable = (void**)global::System.Runtime.CompilerServices.RuntimeHelpers.AllocateTypeAssociatedMemory(typeof(global::DiaSharp.StackWalk.IStackWalkHelper2), sizeof(void*) * 16);
        {
            global::System.Runtime.InteropServices.NativeMemory.Copy(global::System.Runtime.InteropServices.Marshalling.StrategyBasedComWrappers.DefaultIUnknownInterfaceDetailsStrategy.GetIUnknownDerivedDetails(typeof(global::DiaSharp.StackWalk.IStackWalkHelper).TypeHandle).ManagedVirtualMethodTable, vtable, (nuint)(sizeof(void*) * 15));
        }

        {
            vtable[15] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, ulong, ulong*, int> )&ABI_GetPointerAuthenticationMask;
        }

        return vtable;
    }
}

namespace DiaSharp.StackWalk
{
    [global::System.Runtime.InteropServices.Marshalling.IUnknownDerivedAttribute<InterfaceInformation, InterfaceImplementation>]
    public partial interface IStackWalkHelper2
    {
    }
}

namespace DiaSharp.StackWalk
{
    public partial interface IStackWalkHelper2
    {
            [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
        [global::System.Runtime.InteropServices.PreserveSigAttribute()]
        new int GetRegisterValue(global::DiaSharp.CodeView.HostRegister index, out ulong value) => ((global::DiaSharp.StackWalk.IStackWalkHelper)this).GetRegisterValue(index, out value);
            [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
        [global::System.Runtime.InteropServices.PreserveSigAttribute()]
        new int PutRegisterValue(global::DiaSharp.CodeView.HostRegister index, ulong value) => ((global::DiaSharp.StackWalk.IStackWalkHelper)this).PutRegisterValue(index, value);
            [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
        [global::System.Runtime.InteropServices.PreserveSigAttribute()]
        new int ReadMemory(global::DiaSharp.Native.MemoryType type, ulong virtualAddress, uint bufferSize, out uint bytesWritten, byte* buffer) => ((global::DiaSharp.StackWalk.IStackWalkHelper)this).ReadMemory(type, virtualAddress, bufferSize, out bytesWritten, buffer);
            [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
        [global::System.Runtime.InteropServices.PreserveSigAttribute()]
        new int SearchForReturnAddress(global::DiaSharp.SDK.IFrameData frame, out ulong address) => ((global::DiaSharp.StackWalk.IStackWalkHelper)this).SearchForReturnAddress(frame, out address);
            [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
        [global::System.Runtime.InteropServices.PreserveSigAttribute()]
        new int SearchForReturnAddressStart(global::DiaSharp.SDK.IFrameData frame, ulong address, out ulong startAddress) => ((global::DiaSharp.StackWalk.IStackWalkHelper)this).SearchForReturnAddressStart(frame, address, out startAddress);
            [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
        [global::System.Runtime.InteropServices.PreserveSigAttribute()]
        new int GetFrameForVA(ulong va, out global::DiaSharp.SDK.IFrameData frame) => ((global::DiaSharp.StackWalk.IStackWalkHelper)this).GetFrameForVA(va, out frame);
            [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
        [global::System.Runtime.InteropServices.PreserveSigAttribute()]
        new int GetSymbolForVA(ulong va, out global::DiaSharp.SDK.Symbols.ISymbol symbol) => ((global::DiaSharp.StackWalk.IStackWalkHelper)this).GetSymbolForVA(va, out symbol);
            [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
        [global::System.Runtime.InteropServices.PreserveSigAttribute()]
        new int GetPDataForVA(ulong virtualAddress, uint bytesRequested, out uint bytesWritten, byte* buffer) => ((global::DiaSharp.StackWalk.IStackWalkHelper)this).GetPDataForVA(virtualAddress, bytesRequested, out bytesWritten, buffer);
            [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
        [global::System.Runtime.InteropServices.PreserveSigAttribute()]
        new int GetImageForVA(ulong virtualAddressContext, out ulong imageAddress) => ((global::DiaSharp.StackWalk.IStackWalkHelper)this).GetImageForVA(virtualAddressContext, out imageAddress);
            [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
        [global::System.Runtime.InteropServices.PreserveSigAttribute()]
        new int GetAddressForVA(ulong virtualAddress, out uint equivalentSection, out uint fragmentCount) => ((global::DiaSharp.StackWalk.IStackWalkHelper)this).GetAddressForVA(virtualAddress, out equivalentSection, out fragmentCount);
            [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
        [global::System.Runtime.InteropServices.PreserveSigAttribute()]
        new int GetNumberOfFunctionFragmentsForVA(ulong functionAddress, uint functionSize, out uint fragmentCount) => ((global::DiaSharp.StackWalk.IStackWalkHelper)this).GetNumberOfFunctionFragmentsForVA(functionAddress, functionSize, out fragmentCount);
            [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
        [global::System.Runtime.InteropServices.PreserveSigAttribute()]
        new int GetFunctionFragmentsForVA(ulong functionAddress, uint functionSize, uint fragmentCount, ulong* fragments, uint* fragmentLengths) => ((global::DiaSharp.StackWalk.IStackWalkHelper)this).GetFunctionFragmentsForVA(functionAddress, functionSize, fragmentCount, fragments, fragmentLengths);
    }
}