// <auto-generated />
#pragma warning disable CS0612, CS0618
file unsafe class InterfaceInformation : System.Runtime.InteropServices.Marshalling.IIUnknownInterfaceType
{
	public static System.Guid Iid { get; } = new(new System.ReadOnlySpan<byte>(new byte[] { 28, 70, 122, 88, 11, 184, 84, 79, 145, 148, 80, 50, 88, 154, 99, 25 }));

	private static void** _vtable;
	public static void** ManagedVirtualMethodTable => _vtable != null ? _vtable : (_vtable = InterfaceImplementation.CreateManagedVirtualFunctionTable());
}

[System.Runtime.InteropServices.DynamicInterfaceCastableImplementationAttribute]
file unsafe partial interface InterfaceImplementation : DiaSharp.SDK.Callbacks.IReadExeAtOffsetCallback
{
	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	unsafe void DiaSharp.SDK.Callbacks.IReadExeAtOffsetCallback.ReadExecutableAt(ulong fileOffset, uint executableSize, uint* bytesWritten, byte* buffer)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.SDK.Callbacks.IReadExeAtOffsetCallback));
		int __invokeRetVal;
		{
			__invokeRetVal = ((delegate* unmanaged[MemberFunction]<void*, ulong, uint, uint*, byte*, int> )__vtable_native[3])(__this, fileOffset, executableSize, bytesWritten, buffer);
		}

		// NotifyForSuccessfulInvoke - Keep alive any managed objects that need to stay alive across the call.
		System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(__invokeRetVal);
		System.GC.KeepAlive(this);
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_ReadExecutableAt(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, ulong fileOffset, uint executableSize, uint* bytesWritten, byte* buffer)
	{
		DiaSharp.SDK.Callbacks.IReadExeAtOffsetCallback @this = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.SDK.Callbacks.IReadExeAtOffsetCallback>(__this_native);
			@this.ReadExecutableAt(fileOffset, executableSize, bytesWritten, buffer);
			// NotifyForSuccessfulInvoke - Keep alive any managed objects that need to stay alive across the call.
			__retVal = 0; // S_OK
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	internal static void** CreateManagedVirtualFunctionTable()
	{
		void** vtable = (void**)System.Runtime.CompilerServices.RuntimeHelpers.AllocateTypeAssociatedMemory(typeof(DiaSharp.SDK.Callbacks.IReadExeAtOffsetCallback), sizeof(void*) * 4);
		{
			nint v0, v1, v2;
			System.Runtime.InteropServices.ComWrappers.GetIUnknownImpl(out v0, out v1, out v2);
			vtable[0] = (void*)v0;
			vtable[1] = (void*)v1;
			vtable[2] = (void*)v2;
		}

		{
			vtable[3] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, ulong, uint, uint*, byte*, int> )&ABI_ReadExecutableAt;
		}

		return vtable;
	}
}

namespace DiaSharp.SDK.Callbacks
{
	[System.Runtime.InteropServices.Marshalling.IUnknownDerivedAttribute<InterfaceInformation, InterfaceImplementation>]
	public partial interface IReadExeAtOffsetCallback
	{
	}
}