<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>

		<PackageId>DiaSharp.Managed</PackageId>

		<Description>High-level managed bindings for the native DiaSharp implementation.</Description>

		<RootNamespace>DiaSharp</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\DiaSharp\DiaSharp.csproj" />
	</ItemGroup>

</Project>
