// <auto-generated />
#pragma warning disable CS0612, CS0618
file unsafe class InterfaceInformation : global::System.Runtime.InteropServices.Marshalling.IIUnknownInterfaceType
{
    public static global::System.Guid Iid { get; } = new(new global::System.ReadOnlySpan<byte>(new byte[] { 29, 70, 157, 236, 116, 206, 17, 71, 160, 32, 125, 143, 154, 29, 210, 85 }));

    private static void** _vtable;
    public static void** ManagedVirtualMethodTable => _vtable != null ? _vtable : (_vtable = InterfaceImplementation.CreateManagedVirtualFunctionTable());
}

[global::System.Runtime.InteropServices.DynamicInterfaceCastableImplementationAttribute]
file unsafe partial interface InterfaceImplementation : global::DiaSharp.SDK.Enumerators.IEnumStackFrames
{
    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    unsafe int global::DiaSharp.SDK.Enumerators.IEnumStackFrames.GetNext(uint frameCount, void** frames, out uint framesFetched)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.Enumerators.IEnumStackFrames));
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out framesFetched);
        int __retVal;
        // Pin - Pin data in preparation for calling the P/Invoke.
        fixed (uint* __framesFetched_native = &framesFetched)
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, uint, void**, uint*, int> )__vtable_native[3])(__this, frameCount, frames, __framesFetched_native);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.SDK.Enumerators.IEnumStackFrames.Reset()
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.Enumerators.IEnumStackFrames));
        int __retVal;
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, int> )__vtable_native[4])(__this);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }
}

file unsafe partial interface InterfaceImplementation
{
    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_GetNext(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, uint frameCount, void** frames, uint* __framesFetched_native__param)
    {
        global::DiaSharp.SDK.Enumerators.IEnumStackFrames @this = default;
        ref uint __framesFetched_native = ref *__framesFetched_native__param;
        uint framesFetched = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.Enumerators.IEnumStackFrames>(__this_native);
            __retVal = @this.GetNext(frameCount, frames, out framesFetched);
            // Marshal - Convert managed data to native data.
            __framesFetched_native = framesFetched;
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_Reset(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native)
    {
        global::DiaSharp.SDK.Enumerators.IEnumStackFrames @this = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.Enumerators.IEnumStackFrames>(__this_native);
            __retVal = @this.Reset();
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }
}

file unsafe partial interface InterfaceImplementation
{
    internal static void** CreateManagedVirtualFunctionTable()
    {
        void** vtable = (void**)global::System.Runtime.CompilerServices.RuntimeHelpers.AllocateTypeAssociatedMemory(typeof(global::DiaSharp.SDK.Enumerators.IEnumStackFrames), sizeof(void*) * 5);
        {
            nint v0, v1, v2;
            global::System.Runtime.InteropServices.ComWrappers.GetIUnknownImpl(out v0, out v1, out v2);
            vtable[0] = (void*)v0;
            vtable[1] = (void*)v1;
            vtable[2] = (void*)v2;
        }

        {
            vtable[3] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, uint, void**, uint*, int> )&ABI_GetNext;
            vtable[4] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, int> )&ABI_Reset;
        }

        return vtable;
    }
}

namespace DiaSharp.SDK.Enumerators
{
    [global::System.Runtime.InteropServices.Marshalling.IUnknownDerivedAttribute<InterfaceInformation, InterfaceImplementation>]
    public partial interface IEnumStackFrames
    {
    }
}

namespace DiaSharp.SDK.Enumerators
{
    public partial interface IEnumStackFrames
    {
    }
}