// <auto-generated />
#pragma warning disable CS0612, CS0618
file unsafe class InterfaceInformation : global::System.Runtime.InteropServices.Marshalling.IIUnknownInterfaceType
{
    public static global::System.Guid Iid { get; } = new(new global::System.ReadOnlySpan<byte>(new byte[] { 83, 246, 127, 28, 247, 81, 126, 69, 132, 25, 178, 15, 87, 239, 126, 77 }));

    private static void** _vtable;
    public static void** ManagedVirtualMethodTable => _vtable != null ? _vtable : (_vtable = InterfaceImplementation.CreateManagedVirtualFunctionTable());
}

[global::System.Runtime.InteropServices.DynamicInterfaceCastableImplementationAttribute]
file unsafe partial interface InterfaceImplementation : global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles
{
    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles.GetNewEnum(out global::DiaSharp.Interop.IEnumVARIANT enumerator)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles));
        bool __invokeSucceeded = default;
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out enumerator);
        void* __enumerator_native = default;
        int __retVal = default;
        try
        {
            {
                __retVal = ((delegate* unmanaged[MemberFunction]<void*, void**, int> )__vtable_native[3])(__this, &__enumerator_native);
            }

            __invokeSucceeded = true;
            global::System.GC.KeepAlive(this);
            // Unmarshal - Convert native data to managed data.
            enumerator = global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.Interop.IEnumVARIANT>.ConvertToManaged(__enumerator_native);
        }
        finally
        {
            if (__invokeSucceeded)
            {
                // CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
                global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.Interop.IEnumVARIANT>.Free(__enumerator_native);
            }
        }

        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles.GetCount(out int count)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles));
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out count);
        int __retVal;
        // Pin - Pin data in preparation for calling the P/Invoke.
        fixed (int* __count_native = &count)
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, int*, int> )__vtable_native[4])(__this, __count_native);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles.Item(uint index, out global::DiaSharp.SDK.IInputAssemblyFile file)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles));
        bool __invokeSucceeded = default;
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out file);
        void* __file_native = default;
        int __retVal = default;
        try
        {
            {
                __retVal = ((delegate* unmanaged[MemberFunction]<void*, uint, void**, int> )__vtable_native[5])(__this, index, &__file_native);
            }

            __invokeSucceeded = true;
            global::System.GC.KeepAlive(this);
            // Unmarshal - Convert native data to managed data.
            file = global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.SDK.IInputAssemblyFile>.ConvertToManaged(__file_native);
        }
        finally
        {
            if (__invokeSucceeded)
            {
                // CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
                global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.SDK.IInputAssemblyFile>.Free(__file_native);
            }
        }

        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    unsafe int global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles.GetNext(uint fileCount, void** files, out uint filesFetched)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles));
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out filesFetched);
        int __retVal;
        // Pin - Pin data in preparation for calling the P/Invoke.
        fixed (uint* __filesFetched_native = &filesFetched)
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, uint, void**, uint*, int> )__vtable_native[6])(__this, fileCount, files, __filesFetched_native);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles.Skip(uint fileCount)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles));
        int __retVal;
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, uint, int> )__vtable_native[7])(__this, fileCount);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles.Reset()
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles));
        int __retVal;
        {
            __retVal = ((delegate* unmanaged[MemberFunction]<void*, int> )__vtable_native[8])(__this);
        }

        global::System.GC.KeepAlive(this);
        return __retVal;
    }

    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles.Clone(out global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles enumerator)
    {
        var(__this, __vtable_native) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles));
        bool __invokeSucceeded = default;
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out enumerator);
        void* __enumerator_native = default;
        int __retVal = default;
        try
        {
            {
                __retVal = ((delegate* unmanaged[MemberFunction]<void*, void**, int> )__vtable_native[9])(__this, &__enumerator_native);
            }

            __invokeSucceeded = true;
            global::System.GC.KeepAlive(this);
            // Unmarshal - Convert native data to managed data.
            enumerator = global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles>.ConvertToManaged(__enumerator_native);
        }
        finally
        {
            if (__invokeSucceeded)
            {
                // CleanupCalleeAllocated - Perform cleanup of callee allocated resources.
                global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles>.Free(__enumerator_native);
            }
        }

        return __retVal;
    }
}

file unsafe partial interface InterfaceImplementation
{
    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_GetNewEnum(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, void** __enumerator_native__param)
    {
        global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles @this = default;
        ref void* __enumerator_native = ref *__enumerator_native__param;
        global::DiaSharp.Interop.IEnumVARIANT enumerator = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles>(__this_native);
            __retVal = @this.GetNewEnum(out enumerator);
            // Marshal - Convert managed data to native data.
            __enumerator_native = (void*)global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.Interop.IEnumVARIANT>.ConvertToUnmanaged(enumerator);
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_GetCount(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, int* __count_native__param)
    {
        global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles @this = default;
        ref int __count_native = ref *__count_native__param;
        int count = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles>(__this_native);
            __retVal = @this.GetCount(out count);
            // Marshal - Convert managed data to native data.
            __count_native = count;
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_Item(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, uint index, void** __file_native__param)
    {
        global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles @this = default;
        ref void* __file_native = ref *__file_native__param;
        global::DiaSharp.SDK.IInputAssemblyFile file = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles>(__this_native);
            __retVal = @this.Item(index, out file);
            // Marshal - Convert managed data to native data.
            __file_native = (void*)global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.SDK.IInputAssemblyFile>.ConvertToUnmanaged(file);
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_GetNext(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, uint fileCount, void** files, uint* __filesFetched_native__param)
    {
        global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles @this = default;
        ref uint __filesFetched_native = ref *__filesFetched_native__param;
        uint filesFetched = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles>(__this_native);
            __retVal = @this.GetNext(fileCount, files, out filesFetched);
            // Marshal - Convert managed data to native data.
            __filesFetched_native = filesFetched;
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_Skip(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, uint fileCount)
    {
        global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles @this = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles>(__this_native);
            __retVal = @this.Skip(fileCount);
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_Reset(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native)
    {
        global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles @this = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles>(__this_native);
            __retVal = @this.Reset();
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_Clone(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, void** __enumerator_native__param)
    {
        global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles @this = default;
        ref void* __enumerator_native = ref *__enumerator_native__param;
        global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles enumerator = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles>(__this_native);
            __retVal = @this.Clone(out enumerator);
            // Marshal - Convert managed data to native data.
            __enumerator_native = (void*)global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles>.ConvertToUnmanaged(enumerator);
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }
}

file unsafe partial interface InterfaceImplementation
{
    internal static void** CreateManagedVirtualFunctionTable()
    {
        void** vtable = (void**)global::System.Runtime.CompilerServices.RuntimeHelpers.AllocateTypeAssociatedMemory(typeof(global::DiaSharp.SDK.Enumerators.IEnumInputAssemblyFiles), sizeof(void*) * 10);
        {
            nint v0, v1, v2;
            global::System.Runtime.InteropServices.ComWrappers.GetIUnknownImpl(out v0, out v1, out v2);
            vtable[0] = (void*)v0;
            vtable[1] = (void*)v1;
            vtable[2] = (void*)v2;
        }

        {
            vtable[3] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, void**, int> )&ABI_GetNewEnum;
            vtable[4] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, int*, int> )&ABI_GetCount;
            vtable[5] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, uint, void**, int> )&ABI_Item;
            vtable[6] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, uint, void**, uint*, int> )&ABI_GetNext;
            vtable[7] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, uint, int> )&ABI_Skip;
            vtable[8] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, int> )&ABI_Reset;
            vtable[9] = (void*)(delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, void**, int> )&ABI_Clone;
        }

        return vtable;
    }
}

namespace DiaSharp.SDK.Enumerators
{
    [global::System.Runtime.InteropServices.Marshalling.IUnknownDerivedAttribute<InterfaceInformation, InterfaceImplementation>]
    public partial interface IEnumInputAssemblyFiles
    {
    }
}

namespace DiaSharp.SDK.Enumerators
{
    public partial interface IEnumInputAssemblyFiles
    {
    }
}