// <auto-generated />
#pragma warning disable CS0612, CS0618
file unsafe class InterfaceInformation : System.Runtime.InteropServices.Marshalling.IIUnknownInterfaceType
{
	public static System.Guid Iid { get; } = new(new System.ReadOnlySpan<byte>(new byte[] { 193, 144, 197, 7, 141, 67, 71, 79, 189, 205, 67, 151, 188, 129, 173, 117 }));

	private static void** _vtable;
	public static void** ManagedVirtualMethodTable => _vtable != null ? _vtable : (_vtable = InterfaceImplementation.CreateManagedVirtualFunctionTable());
}

[System.Runtime.InteropServices.DynamicInterfaceCastableImplementationAttribute]
file unsafe partial interface InterfaceImplementation : DiaSharp.StackWalk.IStackWalkFrame
{
	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.StackWalk.IStackWalkFrame.GetRegisterValue(DiaSharp.CodeView.HostRegister index, out ulong value)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.StackWalk.IStackWalkFrame));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out value);
		int __retVal;
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (ulong* __value_native = &value)
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, DiaSharp.CodeView.HostRegister, ulong*, int> )__vtable_native[3])(__this, index, __value_native);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.StackWalk.IStackWalkFrame.PutRegisterValue(DiaSharp.CodeView.HostRegister index, ulong value)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.StackWalk.IStackWalkFrame));
		int __retVal;
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, DiaSharp.CodeView.HostRegister, ulong, int> )__vtable_native[4])(__this, index, value);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	unsafe int DiaSharp.StackWalk.IStackWalkFrame.ReadMemory(DiaSharp.Native.MemoryType type, ulong virtualAddress, uint bytesRequested, out uint bytesWritten, byte* buffer)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.StackWalk.IStackWalkFrame));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out bytesWritten);
		int __retVal;
		// Pin - Pin data in preparation for calling the P/Invoke.
		fixed (uint* __bytesWritten_native = &bytesWritten)
		{
			__retVal = ((delegate* unmanaged[MemberFunction]<void*, DiaSharp.Native.MemoryType, ulong, uint, uint*, byte*, int> )__vtable_native[5])(__this, type, virtualAddress, bytesRequested, __bytesWritten_native, buffer);
		}

		System.GC.KeepAlive(this);
		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.StackWalk.IStackWalkFrame.SearchForReturnAddress(DiaSharp.SDK.IFrameData frame, out ulong address)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.StackWalk.IStackWalkFrame));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out address);
		void* __frame_native = default;
		int __retVal = default;
		try
		{
			// Marshal - Convert managed data to native data.
			__frame_native = (void*)System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.IFrameData>.ConvertToUnmanaged(frame);
			// Pin - Pin data in preparation for calling the P/Invoke.
			fixed (ulong* __address_native = &address)
			{
				__retVal = ((delegate* unmanaged[MemberFunction]<void*, void*, ulong*, int> )__vtable_native[6])(__this, __frame_native, __address_native);
			}

			System.GC.KeepAlive(this);
		}
		finally
		{
			// CleanupCallerAllocated - Perform cleanup of caller allocated resources.
			System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.IFrameData>.Free(__frame_native);
		}

		return __retVal;
	}

	[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
	int DiaSharp.StackWalk.IStackWalkFrame.SearchForReturnAddressStart(DiaSharp.SDK.IFrameData frame, ulong address, out ulong start)
	{
		var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(DiaSharp.StackWalk.IStackWalkFrame));
		System.Runtime.CompilerServices.Unsafe.SkipInit(out start);
		void* __frame_native = default;
		int __retVal = default;
		try
		{
			// Marshal - Convert managed data to native data.
			__frame_native = (void*)System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.IFrameData>.ConvertToUnmanaged(frame);
			// Pin - Pin data in preparation for calling the P/Invoke.
			fixed (ulong* __start_native = &start)
			{
				__retVal = ((delegate* unmanaged[MemberFunction]<void*, void*, ulong, ulong*, int> )__vtable_native[7])(__this, __frame_native, address, __start_native);
			}

			System.GC.KeepAlive(this);
		}
		finally
		{
			// CleanupCallerAllocated - Perform cleanup of caller allocated resources.
			System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.IFrameData>.Free(__frame_native);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_GetRegisterValue(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, DiaSharp.CodeView.HostRegister index, ulong* __value_native__param)
	{
		DiaSharp.StackWalk.IStackWalkFrame @this = default;
		ref ulong __value_native = ref *__value_native__param;
		ulong value = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.StackWalk.IStackWalkFrame>(__this_native);
			__retVal = @this.GetRegisterValue(index, out value);
			// Marshal - Convert managed data to native data.
			__value_native = value;
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_PutRegisterValue(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, DiaSharp.CodeView.HostRegister index, ulong value)
	{
		DiaSharp.StackWalk.IStackWalkFrame @this = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.StackWalk.IStackWalkFrame>(__this_native);
			__retVal = @this.PutRegisterValue(index, value);
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_ReadMemory(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, DiaSharp.Native.MemoryType type, ulong virtualAddress, uint bytesRequested, uint* __bytesWritten_native__param, byte* buffer)
	{
		DiaSharp.StackWalk.IStackWalkFrame @this = default;
		ref uint __bytesWritten_native = ref *__bytesWritten_native__param;
		uint bytesWritten = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.StackWalk.IStackWalkFrame>(__this_native);
			__retVal = @this.ReadMemory(type, virtualAddress, bytesRequested, out bytesWritten, buffer);
			// Marshal - Convert managed data to native data.
			__bytesWritten_native = bytesWritten;
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_SearchForReturnAddress(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, void* __frame_native, ulong* __address_native__param)
	{
		DiaSharp.StackWalk.IStackWalkFrame @this = default;
		DiaSharp.SDK.IFrameData frame = default;
		ref ulong __address_native = ref *__address_native__param;
		ulong address = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			frame = System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.IFrameData>.ConvertToManaged(__frame_native);
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.StackWalk.IStackWalkFrame>(__this_native);
			__retVal = @this.SearchForReturnAddress(frame, out address);
			// Marshal - Convert managed data to native data.
			__address_native = address;
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	[System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
	internal static int ABI_SearchForReturnAddressStart(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, void* __frame_native, ulong address, ulong* __start_native__param)
	{
		DiaSharp.StackWalk.IStackWalkFrame @this = default;
		DiaSharp.SDK.IFrameData frame = default;
		ref ulong __start_native = ref *__start_native__param;
		ulong start = default;
		int __retVal = default;
		try
		{
			// Unmarshal - Convert native data to managed data.
			frame = System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<DiaSharp.SDK.IFrameData>.ConvertToManaged(__frame_native);
			@this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<DiaSharp.StackWalk.IStackWalkFrame>(__this_native);
			__retVal = @this.SearchForReturnAddressStart(frame, address, out start);
			// Marshal - Convert managed data to native data.
			__start_native = start;
		}
		catch (System.Exception __exception)
		{
			__retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
		}

		return __retVal;
	}

	internal static void** CreateManagedVirtualFunctionTable()
	{
		void** vtable = (void**)System.Runtime.CompilerServices.RuntimeHelpers.AllocateTypeAssociatedMemory(typeof(DiaSharp.StackWalk.IStackWalkFrame), sizeof(void*) * 8);
		{
			nint v0, v1, v2;
			System.Runtime.InteropServices.ComWrappers.GetIUnknownImpl(out v0, out v1, out v2);
			vtable[0] = (void*)v0;
			vtable[1] = (void*)v1;
			vtable[2] = (void*)v2;
		}

		{
			vtable[3] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, DiaSharp.CodeView.HostRegister, ulong*, int> )&ABI_GetRegisterValue;
			vtable[4] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, DiaSharp.CodeView.HostRegister, ulong, int> )&ABI_PutRegisterValue;
			vtable[5] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, DiaSharp.Native.MemoryType, ulong, uint, uint*, byte*, int> )&ABI_ReadMemory;
			vtable[6] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, void*, ulong*, int> )&ABI_SearchForReturnAddress;
			vtable[7] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, void*, ulong, ulong*, int> )&ABI_SearchForReturnAddressStart;
		}

		return vtable;
	}
}

namespace DiaSharp.StackWalk
{
	[System.Runtime.InteropServices.Marshalling.IUnknownDerivedAttribute<InterfaceInformation, InterfaceImplementation>]
	public partial interface IStackWalkFrame
	{
	}
}