namespace DiaSharp.CodeView;

/// <summary>
/// Specifies the source code language of the application or linked module.
/// </summary>
/// <remarks>
/// The values in this enumeration are returned by a call to the IDiaSymbol::get_language method.
/// </remarks>
internal enum CompileFlagLanguage
{
    /// <summary>
    /// Application language is C.
    /// </summary>
    C,

    /// <summary>
    /// Application language is C++.
    /// </summary>
    CXX,

    /// <summary>
    /// Application language is FORTRAN.
    /// </summary>
    FORTRAN,

    /// <summary>
    /// Application language is Microsoft Macro Assembler.
    /// </summary>
    MASM,

    /// <summary>
    /// Application language is Pascal.
    /// </summary>
    PASCAL,

    /// <summary>
    /// Application language is BASIC.
    /// </summary>
    BASIC,

    /// <summary>
    /// Application language is COBOL.
    /// </summary>
    COBOL,

    /// <summary>
    /// Application is a linker-generated module.
    /// </summary>
    LINK,

    /// <summary>
    /// Application is a resource module converted with CVTRES tool.
    /// </summary>
    CVTRES,

    /// <summary>
    /// Application is a POGO optimized module generated with CVTPGD tool.
    /// </summary>
    CVTPGD,

    /// <summary>
    /// Application language is C#.
    /// </summary>
    CSHARP,

    /// <summary>
    /// Application language is Visual Basic.
    /// </summary>
    VB,

    /// <summary>
    /// Application language is intermediate language assembly (Common Language Runtime (CLR) assembly).
    /// </summary>
    ILASM,

    /// <summary>
    /// Application language is Java.
    /// </summary>
    JAVA,

    /// <summary>
    /// Application language is Jscript.
    /// </summary>
    JSCRIPT,

    /// <summary>
    /// Application language is an unknown Microsoft Intermediate Language (MSIL), possibly a result of using the /LTCG (Link-time Code Generation) switch.
    /// </summary>
    MSIL,

    /// <summary>
    /// Application language is High Level Shader Language.
    /// </summary>
    [Obsolete(__Constants.HlslObsoleteMessage)]
    HLSL,

    /// <summary>
    /// Application language is Objective-C.
    /// </summary>
    OBJC,

    /// <summary>
    /// Application language is Objective-C++.
    /// </summary>
    OBJCXX,

    /// <summary>
    /// Application language is Swift.
    /// </summary>
    SWIFT,

    /// <summary>
    /// Application is a module generated by the <c>aliasobj</c> tool.
    /// </summary>
    ALIASOBJ,

    /// <summary>
    /// Application language is Rust.
    /// </summary>
    RUST,

    /// <summary>
    /// Application language is Go.
    /// </summary>
    GO,
}
