<Project>

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>

		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<AnalysisLevel>latest-all</AnalysisLevel>
		<IsAotCompatible>true</IsAotCompatible>
		<WarningLevel>9999</WarningLevel>
		<NoWarn>CS1591</NoWarn>

		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<LangVersion>preview</LangVersion>
		<Nullable>enable</Nullable>

		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<IsTrimmable>true</IsTrimmable>

		<Authors>Red-K0</Authors>

		<RepositoryUrl>https://github.com/Red-K0/DiaSharp/</RepositoryUrl>
		<RepositoryType>git</RepositoryType>

		<PackageProjectUrl>https://github.com/Red-K0/DiaSharp</PackageProjectUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	
	</PropertyGroup>

	<PropertyGroup Label="Versioning">
		<AssemblyVersion>$(Version)</AssemblyVersion>
		<PackageVersion>$(Version)</PackageVersion>
		<FileVersion>$(Version)</FileVersion>
		<Version>0.1.0</Version>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\README.md">
			<PackagePath>\</PackagePath>
			<Pack>True</Pack>
		</None>
	</ItemGroup>

	<ItemGroup Label="Global Usings">
		<Using Include="System.Reflection" />
		<Using Include="System.Diagnostics" />
		<Using Include="System.Diagnostics.CodeAnalysis" />
		<Using Include="System.Runtime.CompilerServices" />
		<Using Include="System.Runtime.InteropServices" />
	</ItemGroup>

</Project>